import { randomUUID } from "node:crypto";
import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { CommercialMfaFields } from "@/components/commercial-mfa-fields";
import { requireUser } from "@/lib/auth/session";
import { formatCents } from "@/lib/commercial/money";
import { getSubscriptionReceivablesOverview, listSubscriptionInvoices } from "@/lib/commercial/billing-service";
import { prisma } from "@/lib/prisma";
import { createInvoiceDraftAction, issueInvoiceAction, recordPaymentAction, renewWithInvoiceAction, reversePaymentAction, voidInvoiceAction } from "./actions";

export default async function CommercialBillingPage({ searchParams }: { searchParams: Promise<{ message?: string; type?: string }> }) {
  const actor = await requireUser();
  if (actor.role !== "PLATFORM_ADMIN") throw new Error("COMMERCIAL_PLATFORM_AUTHORITY_REQUIRED");
  const query = await searchParams;
  const [overview, invoices, subscriptions] = await Promise.all([
    getSubscriptionReceivablesOverview(actor),
    listSubscriptionInvoices({ actor }),
    prisma.commercialSubscription.findMany({ where: { status: "ACTIVE" }, include: { business: true, group: true }, orderBy: { createdAt: "desc" } }),
  ]);
  return <AppShell user={actor}><section className="content commercial-billing-center">
    <div className="page-header"><div><h1>Subscription Billing</h1><p>Independent SaaS invoices, receivables and payments. This is not POS Invoice or Supplier AP.</p></div><Link href="/admin/commercial">Commercial Center</Link></div>
    {query.message ? <p className={`form-message ${query.type === "error" ? "error" : "success"}`}>{query.message}</p> : null}
    <section className="grid commercial-billing-metrics"><Metric label="Total receivable" value={formatCents(overview.totalReceivableCents)} /><Metric label="Overdue" value={formatCents(overview.overdueCents)} /><Metric label="Due soon" value={formatCents(overview.dueSoonCents)} /><Metric label="Unpaid / partial" value={`${overview.unpaidCount} / ${overview.partiallyPaidCount}`} /></section>
    <section className="panel"><h2>Create frozen invoice draft</h2><p>Draft does not enter receivables. Issuing freezes the snapshot.</p><form action={createInvoiceDraftAction} className="form-grid"><input type="hidden" name="operationKey" value={`SUB_INV_DRAFT:${randomUUID()}`} /><label>Subscription<select name="subscriptionId" required>{subscriptions.map(row => <option value={row.id} key={row.id}>{row.business?.name ?? row.group?.name} · {row.billingIntervalSnapshot}</option>)}</select></label><label>Period start<input type="date" name="billingPeriodStart" required /></label><label>Period end<input type="date" name="billingPeriodEnd" required /></label><label>Invoice date<input type="date" name="invoiceDate" required /></label><label>Due date<input type="date" name="dueDate" required /></label><button>Create draft</button></form></section>
    <section className="panel"><h2>Generate renewal invoice</h2><p>Uses the canonical renewal date, applies a due scheduled plan change deterministically, issues one invoice and advances renewal exactly once.</p><form action={renewWithInvoiceAction} className="form-grid"><input type="hidden" name="operationKey" value={`SUB_RENEW_INV:${randomUUID()}`} /><label>Subscription<select name="subscriptionId" required>{subscriptions.map(row => <option value={row.id} key={row.id}>{row.business?.name ?? row.group?.name} · renewal {row.renewalDate.toLocaleDateString("en-MY")}</option>)}</select></label><label>Invoice date<input type="date" name="invoiceDate" required /></label><label>Due date<input type="date" name="dueDate" required /></label><button>Generate and issue renewal</button></form></section>
    <section className="panel"><h2>Invoices and payment history</h2>{invoices.length ? <div className="table-wrap"><table className="table commercial-billing-table"><thead><tr><th>Invoice</th><th>Customer / period</th><th>Status</th><th>Amount</th><th>Paid / outstanding</th><th>Actions</th></tr></thead><tbody>{invoices.map(invoice => <tr key={invoice.id}><td><strong>{invoice.invoiceNumber}</strong><br /><small>{invoice.invoiceDate.toLocaleDateString("en-MY")} · due {invoice.dueDate.toLocaleDateString("en-MY")}</small></td><td>{invoice.business?.name ?? invoice.group?.name}<br /><small>{invoice.scopeType} · {invoice.billingPeriodStart.toLocaleDateString("en-MY")}–{invoice.billingPeriodEnd.toLocaleDateString("en-MY")}</small></td><td>{invoice.status}<br /><strong>{invoice.status === "ISSUED" ? invoice.canonicalPaymentStatus : "NOT RECEIVABLE"}</strong>{invoice.overdue ? <><br /><span className="status-badge danger">OVERDUE</span></> : null}</td><td>{formatCents(invoice.totalAmountCents)}<br /><small>List {formatCents(invoice.listSubtotalCents)} · adjustment {formatCents(invoice.overrideAdjustmentCents - invoice.promotionDiscountCents)}</small></td><td>{formatCents(invoice.canonicalPaidCents)} / <strong>{formatCents(invoice.canonicalOutstandingCents)}</strong></td><td><BillingActions invoice={invoice} /></td></tr>)}</tbody></table></div> : <p className="empty-state">No subscription invoices.</p>}</section>
  </section></AppShell>;
}

function BillingActions({ invoice }: { invoice: Awaited<ReturnType<typeof listSubscriptionInvoices>>[number] }) {
  return <details><summary>View / manage</summary><div className="commercial-billing-actions"><h3>Frozen breakdown</h3><ul>{invoice.lines.map(line => <li key={line.id}>{line.description} · {line.quantity} × {formatCents(line.unitAmountCents)} = {formatCents(line.lineAmountCents)}</li>)}</ul>{invoice.status === "DRAFT" ? <form action={issueInvoiceAction}><input type="hidden" name="invoiceId" value={invoice.id} /><input type="hidden" name="expectedRevision" value={invoice.revision} /><input type="hidden" name="operationKey" value={`SUB_INV_ISSUE:${randomUUID()}`} /><button>Issue invoice</button></form> : null}{invoice.status === "ISSUED" && invoice.canonicalOutstandingCents > 0 ? <form action={recordPaymentAction} className="form-grid"><input type="hidden" name="invoiceId" value={invoice.id} /><input type="hidden" name="operationKey" value={`SUB_PAY:${randomUUID()}`} /><label>Amount (RM)<input name="amount" inputMode="decimal" required /></label><label>Payment date<input type="date" name="paymentDate" required /></label><label>Method<select name="paymentMethod"><option>BANK_TRANSFER</option><option>DUITNOW_QR</option><option>CASH</option><option>CHEQUE</option><option>CARD_MANUAL</option><option>OTHER</option></select></label><label>Reference<input name="paymentReference" /></label><label>Notes<input name="notes" /></label><CommercialMfaFields label="Record payment" /><button>Record payment</button></form> : null}{invoice.status === "ISSUED" && invoice.canonicalPaidCents === 0 ? <form action={voidInvoiceAction} className="form-grid"><input type="hidden" name="invoiceId" value={invoice.id} /><input type="hidden" name="expectedRevision" value={invoice.revision} /><input type="hidden" name="operationKey" value={`SUB_INV_VOID:${randomUUID()}`} /><label>Reason<input name="reason" minLength={5} required /></label><CommercialMfaFields label="Void issued invoice" /><button>Void invoice</button></form> : null}<h3>Payments</h3>{invoice.payments.length ? invoice.payments.map(payment => <div className="commercial-payment-row" key={payment.id}><span>{payment.paymentNumber} · {formatCents(payment.amountCents)} · {payment.status}</span>{payment.status === "COMPLETED" && !payment.reversal ? <form action={reversePaymentAction} className="form-grid"><input type="hidden" name="paymentId" value={payment.id} /><input type="hidden" name="operationKey" value={`SUB_PAY_REVERSE:${randomUUID()}`} /><label>Reversal reason<input name="reason" minLength={5} required /></label><CommercialMfaFields label="Reverse payment" /><button>Reverse payment</button></form> : payment.reversal ? <small>Reversed: {payment.reversal.reason}</small> : null}</div>) : <p>No payments.</p>}</div></details>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="panel metric"><span>{label}</span><strong>{value}</strong></div>; }
