import { randomUUID } from "node:crypto";
import Link from "next/link";
import { requireBusinessUserForModule } from "@/lib/auth/business-user";
import { prisma } from "@/lib/prisma";
import { createSupplierAction } from "../purchasing-actions";

export default async function SuppliersPage({ searchParams }: { searchParams: Promise<{ message?: string; page?: string; q?: string; status?: string; type?: string }> }) {
  const { businessId } = await requireBusinessUserForModule("INVENTORY", "VIEW_SUPPLIERS");
  const params = await searchParams; const page = Math.max(1, Number(params.page) || 1); const q = params.q?.trim() ?? ""; const status: "ACTIVE" | "INACTIVE" | undefined = params.status === "INACTIVE" ? "INACTIVE" : params.status === "ACTIVE" ? "ACTIVE" : undefined; const take = 25;
  const where = { businessId, ...(status ? { status } : {}), ...(q ? { OR: [{ name: { contains: q, mode: "insensitive" as const } }, { code: { contains: q, mode: "insensitive" as const } }, { phone: { contains: q } }] } : {}) };
  const [suppliers, total] = await Promise.all([prisma.supplier.findMany({ where, orderBy: { name: "asc" }, skip: (page - 1) * take, take, include: { _count: { select: { purchaseOrders: true } } } }), prisma.supplier.count({ where })]);
  return <section className="content"><div className="page-header"><div><h1>Suppliers</h1><p>Business-scoped supplier directory. Historical suppliers are deactivated, never hard-deleted.</p></div><Link className="secondary-link-button" href="/inventory/purchase-orders">Purchase orders</Link></div>
    {params.message ? <p className={`form-message ${params.type === "error" ? "error" : "success"}`}>{params.message}</p> : null}
    <form className="filter-bar"><input name="q" defaultValue={q} placeholder="Supplier, code, or phone" /><select name="status" defaultValue={status ?? ""}><option value="">All status</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select><button type="submit">Filter</button></form>
    <div className="panel"><div className="section-header"><h2>Supplier list</h2><span>{total} records</span></div>{suppliers.length ? <div className="table-wrap"><table><thead><tr><th>Supplier</th><th>Code</th><th>Contact</th><th>Status</th><th>POs</th></tr></thead><tbody>{suppliers.map((supplier) => <tr key={supplier.id}><td><Link href={`/inventory/suppliers/${supplier.id}`}>{supplier.name}</Link></td><td>{supplier.code ?? "—"}</td><td>{supplier.contactPerson ?? supplier.phone ?? "—"}</td><td><span className={`status ${supplier.status === "ACTIVE" ? "active" : "inactive"}`}>{supplier.status}</span></td><td>{supplier._count.purchaseOrders}</td></tr>)}</tbody></table></div> : <p className="empty-state">No suppliers match this filter.</p>}{total > take ? <div className="form-actions">{page > 1 ? <Link href={`?page=${page - 1}&q=${encodeURIComponent(q)}&status=${status ?? ""}`}>Previous</Link> : null}<span>Page {page}</span>{page * take < total ? <Link href={`?page=${page + 1}&q=${encodeURIComponent(q)}&status=${status ?? ""}`}>Next</Link> : null}</div> : null}</div>
    <div className="panel"><h2>Add supplier</h2><form action={createSupplierAction} className="form-grid"><input type="hidden" name="operationKey" value={`CREATE_SUPPLIER:${randomUUID()}`} /><label>Name<input name="name" required maxLength={160} /></label><label>Code<input name="code" maxLength={40} /></label><label>Contact person<input name="contactPerson" maxLength={120} /></label><label>Phone<input name="phone" maxLength={40} /></label><label>Email<input name="email" type="email" maxLength={160} /></label><label className="full-width">Address<textarea name="address" rows={2} /></label><label className="full-width">Notes<textarea name="notes" rows={2} /></label><div className="form-actions full-width"><button type="submit">Create supplier</button></div></form></div>
  </section>;
}
