import { randomUUID } from "node:crypto";
import Link from "next/link";
import { notFound } from "next/navigation";
import { requireBusinessUserForModule } from "@/lib/auth/business-user";
import type { StaffPermission } from "@/lib/auth/staff-permissions";
import { getOperationalBranches } from "@/lib/branches";
import { prisma } from "@/lib/prisma";
import { approveStockCountAction, cancelStockCountAction, recordStockCountLineAction, reopenStockCountAction, startStockCountAction, submitStockCountAction } from "../../stock-count-actions";
import styles from "../stock-count.module.css";

export default async function StockCountDetailPage({ params, searchParams }: { params: Promise<{ sessionId: string }>; searchParams: Promise<{ message?: string; type?: string; variance?: string }> }) {
  const { businessId, user } = await requireBusinessUserForModule("INVENTORY", "VIEW_STOCK_COUNTS"); const { sessionId } = await params; const query = await searchParams;
  const branches = await getOperationalBranches(businessId, user); const branchIds = new Set(branches.map((branch) => branch.id));
  const session = await prisma.stockCountSession.findFirst({ where: { businessId, id: sessionId }, include: { approvedBy: { select: { name: true } }, branch: { select: { name: true } }, createdBy: { select: { name: true } }, lines: { include: { countedBy: { select: { name: true } }, product: { select: { name: true, sku: true, status: true, trackInventory: true } }, revisions: { orderBy: { revision: "desc" } } }, orderBy: { product: { name: "asc" } } } } });
  if (!session || !branchIds.has(session.branchId)) notFound();
  const filter = ["positive", "negative", "zero", "variance"].includes(query.variance ?? "") ? query.variance : "all";
  const lines = session.lines.filter((line) => filter === "positive" ? (line.varianceQuantity ?? 0) > 0 : filter === "negative" ? (line.varianceQuantity ?? 0) < 0 : filter === "zero" ? line.varianceQuantity === 0 : filter === "variance" ? line.varianceQuantity !== null && line.varianceQuantity !== 0 : true);
  const counted = session.lines.filter((line) => line.actualQuantity !== null).length; const varianceLines = session.lines.filter((line) => line.varianceQuantity !== null && line.varianceQuantity !== 0); const matched = session.lines.filter((line) => line.varianceQuantity === 0).length;
  const can = (permission: StaffPermission) => user.role === "BUSINESS_OWNER" || (user.role === "STAFF" && user.permissions.includes(permission));
  const invalidating = session.status === "SUBMITTED" && session.lines.some((line) => line.countedAt) ? await prisma.inventoryMovement.findMany({ where: { businessId, branchId: session.branchId, productId: { in: session.lines.map((line) => line.productId) }, type: { in: ["ADJUSTMENT_IN", "ADJUSTMENT_OUT", "SYSTEM_CORRECTION"] }, createdAt: { gt: new Date(Math.min(...session.lines.filter((line) => line.countedAt).map((line) => line.countedAt!.getTime()))) } }, select: { createdAt: true, productId: true } }) : [];
  const stale = session.lines.some((line) => line.countedAt && invalidating.some((movement) => movement.productId === line.productId && movement.createdAt > line.countedAt!));
  return <section className="content"><div className="page-header"><div><h1>{session.countNumber}</h1><p>{session.branch.name} · {session.countType.replaceAll("_", " ")} · revision {session.revision}</p></div><div className="form-actions"><Link href="/inventory/stock-counts">Stock counts</Link><Link href="/inventory/movements">Movement trace</Link></div></div>
    {query.message ? <p className={`form-message ${query.type === "error" ? "error" : "success"}`}>{query.message}</p> : null}{stale ? <p className="form-message error">A correction movement occurred after counting. Approval is blocked until the affected line is recounted.</p> : null}
    <div className="stat-grid"><div className="stat-card"><span>Products counted</span><strong>{counted} / {session.lines.length}</strong></div><div className="stat-card"><span>Matched</span><strong>{matched}</strong></div><div className="stat-card"><span>Negative variance</span><strong>{varianceLines.filter((line) => line.varianceQuantity! < 0).length}</strong></div><div className="stat-card"><span>Positive variance</span><strong>{varianceLines.filter((line) => line.varianceQuantity! > 0).length}</strong></div><div className="stat-card"><span>Net quantity variance</span><strong>{session.lines.reduce((sum, line) => sum + (line.varianceQuantity ?? 0), 0)}</strong></div><div className="stat-card"><span>Status</span><strong>{session.status.replaceAll("_", " ")}</strong></div></div>
    <div className="panel"><div className="section-header"><h2>Lifecycle</h2><span>Created by {session.createdBy.name}</span></div><div className="form-actions">
      {session.status === "DRAFT" && can("STOCK_COUNTS_COUNT") ? <Action action={startStockCountAction} label="Start count" operationKey={`START_COUNT:${randomUUID()}`} revision={session.revision} sessionId={session.id} /> : null}
      {session.status === "IN_PROGRESS" && can("STOCK_COUNTS_COUNT") ? <Action action={submitStockCountAction} disabled={counted !== session.lines.length} label="Submit for approval" operationKey={`SUBMIT_COUNT:${randomUUID()}`} revision={session.revision} sessionId={session.id} /> : null}
      {session.status === "SUBMITTED" && can("STOCK_COUNTS_APPROVE") ? <ReasonAction action={reopenStockCountAction} label="Reopen for recount" operationKey={`REOPEN_COUNT:${randomUUID()}`} revision={session.revision} sessionId={session.id} /> : null}
      {session.status === "SUBMITTED" && can("STOCK_COUNTS_APPROVE") ? <ReasonAction action={approveStockCountAction} disabled={stale} label="Approve variance" operationKey={`APPROVE_COUNT:${randomUUID()}`} revision={session.revision} sessionId={session.id} /> : null}
      {!["APPROVED", "CANCELLED"].includes(session.status) && can("STOCK_COUNTS_CANCEL") ? <ReasonAction action={cancelStockCountAction} label="Cancel count" operationKey={`CANCEL_COUNT:${randomUUID()}`} revision={session.revision} sessionId={session.id} /> : null}
    </div><p className="help-text">Approval applies each frozen variance as an ADJUSTMENT_IN or ADJUSTMENT_OUT movement. It never sets a balance directly. A counter cannot approve their own non-zero variance.</p></div>
    <form className="filter-bar"><select name="variance" defaultValue={filter}><option value="all">All lines</option><option value="variance">Variance only</option><option value="positive">Positive</option><option value="negative">Negative</option><option value="zero">Zero</option></select><button>Filter</button></form>
    <div className={styles.lineGrid}>{lines.map((line) => <article className={styles.lineCard} key={line.id}><div className={styles.product}><h3>{line.product.name}</h3><p>{line.product.sku ?? "No SKU"}{line.product.status !== "ACTIVE" ? " · Product inactive" : ""}{!line.product.trackInventory ? " · Tracking disabled" : ""}</p></div><div className={styles.facts}><Fact label="Expected at count" value={line.expectedQuantityAtCount ?? "Not frozen"} /><Fact label="Actual" value={line.actualQuantity ?? "Not counted"} /><Fact label="Variance" value={line.varianceQuantity === null ? "—" : `${line.varianceQuantity > 0 ? "+" : ""}${line.varianceQuantity}${Math.abs(line.varianceQuantity) >= 10 ? " · Large variance" : ""}`} /></div>
      {session.status === "IN_PROGRESS" && can("STOCK_COUNTS_COUNT") ? <form action={recordStockCountLineAction} className={styles.countForm}><input type="hidden" name="operationKey" value={`COUNT_LINE:${randomUUID()}`} /><input type="hidden" name="sessionId" value={session.id} /><input type="hidden" name="lineId" value={line.id} /><input type="hidden" name="expectedLineRevision" value={line.revision} /><label>Actual qty<input required name="actualQuantity" type="number" min="0" step="1" defaultValue={line.actualQuantity ?? ""} /></label><label>Note<input name="notes" maxLength={500} defaultValue={line.notes ?? ""} /></label><button>Save &amp; freeze</button></form> : <div><strong>{line.countedBy?.name ?? "—"}</strong><br /><span>{line.countedAt?.toLocaleString("en-MY", { timeZone: "Asia/Kuala_Lumpur" }) ?? "Not counted"}</span></div>}
      <div className={styles.history}>Evidence revisions: {line.revisions.length}{line.revisions.length > 1 ? ` · Previous ${line.revisions.slice(1).map((revision) => `${revision.actualQuantity} @ expected ${revision.expectedQuantityAtCount}`).join(", ")}` : ""}</div></article>)}</div>
    {session.status === "APPROVED" ? <div className="panel"><h2>Approved evidence</h2><p>Approved by {session.approvedBy?.name ?? "—"} at {session.approvedAt?.toLocaleString("en-MY", { timeZone: "Asia/Kuala_Lumpur" })}. This session and its count history are immutable.</p></div> : null}
  </section>;
}

function Fact({ label, value }: { label: string; value: number | string }) { return <div><span>{label}</span><br /><strong>{value}</strong></div>; }
function Action({ action, disabled, label, operationKey, revision, sessionId }: { action: (data: FormData) => void | Promise<void>; disabled?: boolean; label: string; operationKey: string; revision: number; sessionId: string }) { return <form action={action}><input type="hidden" name="operationKey" value={operationKey} /><input type="hidden" name="sessionId" value={sessionId} /><input type="hidden" name="expectedRevision" value={revision} /><button disabled={disabled}>{label}</button></form>; }
function ReasonAction({ action, disabled, label, operationKey, revision, sessionId }: { action: (data: FormData) => void | Promise<void>; disabled?: boolean; label: string; operationKey: string; revision: number; sessionId: string }) { return <form action={action} className="filter-bar"><input type="hidden" name="operationKey" value={operationKey} /><input type="hidden" name="sessionId" value={sessionId} /><input type="hidden" name="expectedRevision" value={revision} /><input required minLength={3} maxLength={500} name="reason" placeholder={`${label} reason`} /><button disabled={disabled}>{label}</button></form>; }
