export const businessCapabilities = [
  "VIEW_DASHBOARD",
  "VIEW_REPORTS",
  "VIEW_APPOINTMENTS",
  "VIEW_WORK_ORDERS",
  "VIEW_CRM",
  "VIEW_INVOICES",
  "VIEW_CATALOG",
  "VIEW_INVENTORY",
  "VIEW_TEAM_DIRECTORY",
  "VIEW_ATTENDANCE_EMPLOYEES",
  "VIEW_ATTENDANCE_SETTINGS",
  "VIEW_CLAIM",
  "REVIEW_CLAIM",
  "VERIFY_CLAIM",
  "MANAGE_CLAIM_SETTINGS",
  "LINK_CLAIM_TO_PAYROLL",
  "VIEW_PAYROLL",
  "VIEW_COMPENSATION",
  "EDIT_COMPENSATION",
  "VIEW_PAYROLL_RUN",
  "CREATE_PAYROLL_RUN",
  "EDIT_PAYROLL_ENTRY",
  "SUBMIT_PAYROLL_REVIEW",
  "RETURN_PAYROLL_TO_DRAFT",
  "APPROVE_PAYROLL",
  "REOPEN_PAYROLL",
  "EXPORT_PAYROLL",
  "VIEW_PAYSLIP",
  "PUBLISH_PAYSLIP",
  "VIEW_BANK_ACCOUNT",
  "EDIT_BANK_ACCOUNT",
  "VIEW_PAYMENT_BATCH",
  "PROCESS_PAYMENT",
  "EXPORT_PAYMENT_FILE",
  "VIEW_STATUTORY_PROFILE",
  "EDIT_STATUTORY_PROFILE",
  "VIEW_TAX_PROFILE",
  "EDIT_TAX_PROFILE",
  "VIEW_STATUTORY_SUBMISSION",
  "EXPORT_STATUTORY",
  "SUBMIT_STATUTORY",
  "RESOLVE_STATUTORY_SUBMISSION",
  "PROCESS_CASHIER_PAYMENT",
  "PROCESS_REFUND",
  "ADJUST_INVENTORY",
  "RUN_CLOSING",
  "MODIFY_TEAM",
  "MANAGE_TEAM_PERMISSIONS",
  "MODIFY_ATTENDANCE_EMPLOYEES",
  "MODIFY_ATTENDANCE_SETTINGS",
  "MODIFY_PAYROLL",
  "MANAGE_WHATSAPP",
  "MODIFY_BUSINESS_SETTINGS",
] as const;

export type BusinessCapability = (typeof businessCapabilities)[number];

const groupManagerCapabilities = new Set<BusinessCapability>([
  "VIEW_DASHBOARD",
  "VIEW_REPORTS",
  "VIEW_APPOINTMENTS",
  "VIEW_WORK_ORDERS",
  "VIEW_CRM",
  "VIEW_INVOICES",
  "VIEW_CATALOG",
  "VIEW_INVENTORY",
  "VIEW_TEAM_DIRECTORY",
  "VIEW_ATTENDANCE_EMPLOYEES",
  "VIEW_ATTENDANCE_SETTINGS",
  "MODIFY_ATTENDANCE_EMPLOYEES",
  "MODIFY_ATTENDANCE_SETTINGS",
]);

export function isReadCapability(capability: BusinessCapability) {
  return capability.startsWith("VIEW_");
}

export function canGroupManager(
  capability: BusinessCapability,
) {
  return groupManagerCapabilities.has(capability);
}

export function canGroupOwner(capability: BusinessCapability) {
  return businessCapabilities.includes(capability);
}

const directStaffPermissionMap: Record<BusinessCapability, readonly string[]> = {
  VIEW_DASHBOARD: ["DASHBOARD"],
  VIEW_REPORTS: ["REPORTS"],
  VIEW_APPOINTMENTS: ["APPOINTMENTS"],
  VIEW_WORK_ORDERS: ["JOBS"],
  VIEW_CRM: ["CRM"],
  VIEW_INVOICES: ["INVOICES"],
  VIEW_CATALOG: ["SERVICES", "PACKAGES", "PRODUCTS", "DISCOUNTS"],
  VIEW_INVENTORY: ["PRODUCTS"],
  VIEW_TEAM_DIRECTORY: ["TEAM"],
  VIEW_ATTENDANCE_EMPLOYEES: [
    "ATTENDANCE_EMPLOYEE_READ",
    "ATTENDANCE_EMPLOYEE_MANAGE",
  ],
  VIEW_ATTENDANCE_SETTINGS: [
    "ATTENDANCE_SETTINGS_READ",
    "ATTENDANCE_SETTINGS_MANAGE",
  ],
  VIEW_CLAIM: ["VIEW_CLAIM"],
  REVIEW_CLAIM: ["REVIEW_CLAIM"],
  VERIFY_CLAIM: ["VERIFY_CLAIM"],
  MANAGE_CLAIM_SETTINGS: ["MANAGE_CLAIM_SETTINGS"],
  LINK_CLAIM_TO_PAYROLL: ["LINK_CLAIM_TO_PAYROLL"],
  VIEW_PAYROLL: ["PAYROLL_READ"],
  VIEW_COMPENSATION: ["VIEW_COMPENSATION"],
  EDIT_COMPENSATION: ["EDIT_COMPENSATION"],
  VIEW_PAYROLL_RUN: ["VIEW_PAYROLL_RUN", "PAYROLL_MANAGE"],
  CREATE_PAYROLL_RUN: ["CREATE_PAYROLL_RUN", "PAYROLL_MANAGE"],
  EDIT_PAYROLL_ENTRY: ["EDIT_PAYROLL_ENTRY", "PAYROLL_MANAGE"],
  SUBMIT_PAYROLL_REVIEW: ["SUBMIT_PAYROLL_REVIEW", "PAYROLL_MANAGE"],
  RETURN_PAYROLL_TO_DRAFT: ["RETURN_PAYROLL_TO_DRAFT"],
  APPROVE_PAYROLL: ["APPROVE_PAYROLL"],
  REOPEN_PAYROLL: ["REOPEN_PAYROLL"],
  EXPORT_PAYROLL: ["EXPORT_PAYROLL"],
  VIEW_PAYSLIP: ["VIEW_PAYSLIP"],
  PUBLISH_PAYSLIP: ["PUBLISH_PAYSLIP"],
  VIEW_BANK_ACCOUNT: ["VIEW_BANK_ACCOUNT"],
  EDIT_BANK_ACCOUNT: ["EDIT_BANK_ACCOUNT"],
  VIEW_PAYMENT_BATCH: ["VIEW_PAYMENT_BATCH"],
  PROCESS_PAYMENT: ["PROCESS_PAYMENT"],
  EXPORT_PAYMENT_FILE: ["EXPORT_PAYMENT_FILE"],
  VIEW_STATUTORY_PROFILE: ["VIEW_STATUTORY_PROFILE"],
  EDIT_STATUTORY_PROFILE: ["EDIT_STATUTORY_PROFILE"],
  VIEW_TAX_PROFILE: ["VIEW_TAX_PROFILE"],
  EDIT_TAX_PROFILE: ["EDIT_TAX_PROFILE"],
  VIEW_STATUTORY_SUBMISSION: ["VIEW_STATUTORY_SUBMISSION"],
  EXPORT_STATUTORY: ["EXPORT_STATUTORY"],
  SUBMIT_STATUTORY: ["SUBMIT_STATUTORY"],
  RESOLVE_STATUTORY_SUBMISSION: ["RESOLVE_STATUTORY_SUBMISSION"],
  PROCESS_CASHIER_PAYMENT: ["POS", "JOBS"],
  PROCESS_REFUND: ["INVOICES"],
  ADJUST_INVENTORY: ["PRODUCTS"],
  RUN_CLOSING: ["CLOSING"],
  MODIFY_TEAM: ["TEAM"],
  MANAGE_TEAM_PERMISSIONS: ["MANAGE_TEAM_PERMISSIONS"],
  MODIFY_ATTENDANCE_EMPLOYEES: ["ATTENDANCE_EMPLOYEE_MANAGE"],
  MODIFY_ATTENDANCE_SETTINGS: ["ATTENDANCE_SETTINGS_MANAGE"],
  MANAGE_WHATSAPP: ["WHATSAPP_SESSION"],
  MODIFY_PAYROLL: ["PAYROLL_MANAGE"],
  MODIFY_BUSINESS_SETTINGS: [],
};

export function canDirectStaff(
  permissions: readonly string[],
  capability: BusinessCapability,
) {
  const acceptedPermissions = directStaffPermissionMap[capability];
  return acceptedPermissions.some((permission) =>
    permissions.includes(permission),
  );
}
