import Link from "next/link";
import { requireBusinessUserForModule } from "@/lib/auth/business-user";
import { getOperationalBranches } from "@/lib/branches";
import { prisma } from "@/lib/prisma";

export default async function PurchaseOrdersPage({ searchParams }: { searchParams: Promise<{ branchId?: string; message?: string; page?: string; q?: string; status?: string; supplierId?: string; type?: string }> }) {
  const { businessId, user } = await requireBusinessUserForModule("INVENTORY", "VIEW_PURCHASE_ORDERS"); const params = await searchParams; const branches = await getOperationalBranches(businessId, user); const allowed = branches.map((branch) => branch.id); const page = Math.max(1, Number(params.page) || 1); const take = 25; const q = params.q?.trim() ?? "";
  const statuses = ["DRAFT", "APPROVED", "PARTIALLY_RECEIVED", "RECEIVED", "CANCELLED", "CLOSED"] as const; const status = statuses.includes(params.status as typeof statuses[number]) ? params.status as typeof statuses[number] : undefined;
  const where = { businessId, branchId: { in: params.branchId && allowed.includes(params.branchId) ? [params.branchId] : allowed }, ...(status ? { status } : {}), ...(params.supplierId ? { supplierId: params.supplierId } : {}), ...(q ? { OR: [{ poNumber: { contains: q, mode: "insensitive" as const } }, { supplier: { name: { contains: q, mode: "insensitive" as const } } }] } : {}) };
  const [orders, total, suppliers] = await Promise.all([prisma.purchaseOrder.findMany({ where, orderBy: { createdAt: "desc" }, skip: (page - 1) * take, take, include: { branch: { select: { name: true } }, supplier: { select: { name: true } }, _count: { select: { receipts: true } } } }), prisma.purchaseOrder.count({ where }), prisma.supplier.findMany({ where: { businessId }, orderBy: { name: "asc" }, select: { id: true, name: true } })]);
  return <section className="content"><div className="page-header"><div><h1>Purchase orders</h1><p>Draft, approve, receive, cancel, or close. Only goods receipt changes stock.</p></div><div className="form-actions"><Link href="/inventory/accounts-payable">Accounts payable</Link><Link href="/inventory/supplier-bills">Supplier bills</Link><Link href="/inventory/suppliers">Suppliers</Link><Link className="button-link" href="/inventory/purchase-orders/new">New purchase order</Link></div></div>{params.message ? <p className={`form-message ${params.type === "error" ? "error" : "success"}`}>{params.message}</p> : null}
    <form className="filter-bar"><input name="q" defaultValue={q} placeholder="PO number or supplier" /><select name="status" defaultValue={status ?? ""}><option value="">All status</option>{statuses.map((item) => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select><select name="supplierId" defaultValue={params.supplierId ?? ""}><option value="">All suppliers</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select>{branches.length > 1 ? <select name="branchId" defaultValue={params.branchId ?? ""}><option value="">All branches</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select> : null}<button type="submit">Filter</button></form>
    <div className="panel"><div className="section-header"><h2>Orders</h2><span>{total} records</span></div>{orders.length ? <div className="table-wrap"><table><thead><tr><th>PO</th><th>Supplier</th><th>Branch</th><th>Order date</th><th>Status</th><th>Expected total</th><th>Receipts</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><Link href={`/inventory/purchase-orders/${order.id}`}>{order.poNumber}</Link></td><td>{order.supplier.name}</td><td>{order.branch.name}</td><td>{order.orderDate.toLocaleDateString("en-MY")}</td><td><span className={`status ${order.status === "RECEIVED" ? "active" : order.status === "CANCELLED" || order.status === "CLOSED" ? "inactive" : "warning"}`}>{order.status.replaceAll("_", " ")}</span></td><td>RM{Number(order.subtotal).toFixed(2)}</td><td>{order._count.receipts}</td></tr>)}</tbody></table></div> : <p className="empty-state">No purchase orders match this filter.</p>}{total > take ? <div className="form-actions">{page > 1 ? <Link href={`?page=${page - 1}`}>Previous</Link> : null}<span>Page {page}</span>{page * take < total ? <Link href={`?page=${page + 1}`}>Next</Link> : null}</div> : null}</div>
  </section>;
}
