import Link from "next/link";
import { notFound } from "next/navigation";
import { requireBusinessUserWithAnyCapability } from "@/lib/auth/business-user";
import { hasBusinessCapability } from "@/lib/business-groups/business-access";
import { prisma } from "@/lib/prisma";
import { localPerformanceDate, performanceTimezone } from "@/lib/performance/time";
import { readPerformanceDashboard } from "@/lib/performance/dashboard";
import { formatTargetMoney as money, type TargetSnapshot } from "@/lib/performance/targets-contract";
import { TargetEditor } from "./target-editor";
import styles from "./performance.module.css";

export const dynamic = "force-dynamic";
type Params = { range?: string; q?: string; branch?: string; year?: string; month?: string; tab?: string; employee?: string; page?: string; status?: string; component?: string };
const percent = (v: number | null) => v === null ? "未确认 / 不适用" : `${v.toFixed(2)}%`;
const statuses: Record<string,string> = { CAPTURED_VERIFIED:"已捕获并核对", CAPTURED_VERIFIED_UNASSIGNED:"已核对 · 员工未分配", CAPTURED_PENDING:"待核对", UNCAPTURED:"尚未捕获", EXCLUDED_NONCASH:"非现金核销 · 已排除" };
type Data = Awaited<ReturnType<typeof readPerformanceDashboard>>;
function Composition({value}:{value:Data["annual"]["team"]}) {
  return <dl className={styles.composition}><div><dt>销售实收</dt><dd>{money(value.salesReceived)}</dd></div><div><dt>实收小费</dt><dd>{money(value.tipsReceived)}</dd></div><div><dt>退款冲减</dt><dd>− {money(value.refunds)}</dd></div></dl>;
}
export default async function PerformancePage({searchParams}:{searchParams:Promise<Params>}) {
  if(process.env.TETAMU_PERFORMANCE_PHASE2!=="true") notFound();
  const {businessId,user,access}=await requireBusinessUserWithAnyCapability(["PERFORMANCE_VIEW_TEAM","PERFORMANCE_MANAGE_TARGETS"]);
  if(access.source!=="DIRECT_BUSINESS") notFound();
  const branches=await prisma.branch.findMany({where:{businessId,...(user.role==="BUSINESS_OWNER"?{}:{id:user.branchId??"00000000-0000-0000-0000-000000000000"})},select:{id:true,name:true},orderBy:{name:"asc"}});
  const p=await searchParams;
  const branch=branches.find(b=>b.id===(p.branch??user.branchId))??(!p.branch?branches[0]:undefined);
  if(!branch) notFound();
  const business=await prisma.business.findUniqueOrThrow({where:{id:businessId},select:{timezone:true}});
  const now=new Date(),today=localPerformanceDate(now,performanceTimezone(business.timezone));
  const year=Number(p.year??today.slice(0,4)),month=Number(p.month??today.slice(5,7));
  if(!Number.isInteger(year)||year<2001||year>2200||!Number.isInteger(month)||month<1||month>12) notFound();
  const tab=["overview","targets","details"].includes(p.tab??"")?p.tab!:"overview";
  const data=await readPerformanceDashboard({businessId,branchId:branch.id,actorUserId:user.userId},{year,month,asOf:now,employeeId:p.employee||undefined,page:Number(p.page??1),status:p.status||undefined,component:p.component||undefined,detailRange:p.range==="year"?"year":"month"});
  const canManage=hasBusinessCapability(access,"PERFORMANCE_MANAGE_TARGETS");
  const href=(extra:Params)=>`/team/performance?${new URLSearchParams(Object.entries({...p,branch:branch.id,year:String(year),month:String(month),tab,...extra}).filter(([,v])=>!!v) as [string,string][]).toString()}`;
  const date=(s:string)=>new Intl.DateTimeFormat("zh-CN",{timeZone:data.timezone,dateStyle:"medium",timeStyle:"short"}).format(new Date(s));
  const selectedMember=data.members.find(m=>m.id===p.employee);
  return <main className={styles.page}>
    <header className={styles.header}><div><p className={styles.eyebrow}>PEOPLE / PERFORMANCE</p><h1>业绩管理</h1><p>本店实际销售收款与小费，扣除对应退款；不含税，不涉及工资或佣金。</p></div><span className={styles.badge}>{canManage?"可管理目标":"门店只读"}</span></header>
    <form className={styles.filters} method="get"><input type="hidden" name="tab" value={tab}/><label>门店<select name="branch" defaultValue={branch.id}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>年份<input aria-label="Performance year" name="year" type="number" min="2001" max="2200" defaultValue={year}/></label><label>月份<select name="month" defaultValue={month}>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{i+1}月</option>)}</select></label><button type="submit">查看</button></form>
    <nav className={styles.tabs} aria-label="Performance sections">{[["overview","总览"],["targets","目标设置"],["details","业绩明细"]].map(([key,label])=><Link key={key} href={href({tab:key,page:"",employee:"",status:"",component:""})} aria-current={tab===key?"page":undefined}>{label}</Link>)}</nav>
    <p className={styles.meta}>统计截止 {date(data.asOf)} · {data.timezone} · {data.annual.started?`覆盖 ${date(data.annual.from)} 至 ${date(new Date(Math.min(new Date(data.annual.toExclusive).getTime()-1,now.getTime())).toISOString())}`:"该经营年度尚未开始，目标可先设置"}</p>
    {!data.annual.complete&&<aside className={styles.warning}>数据待补齐：目前仅显示已核对小计，暂不确认正式等级或完成率。未捕获 {data.annual.uncapturedCount}，待核对 {data.annual.pendingCount}，来源证据缺口 {data.annual.basisGapCount}。<Link href={href({tab:"details",status:"",page:"",range:"year"})}>查看来源</Link></aside>}
    {tab==="overview"&&<>
      <section className={styles.card}><p className={styles.eyebrow}>{year} 团队年度累计 · {branch.name}</p><h2 className={styles.amount}>{money(data.annual.team.total)}</h2><p>{!data.annual.started?"该年度尚未开始":data.annual.complete?"截至统计时刻数据完整":"已核对小计 / 数据待补齐"} · 今年累计完成率 {percent(data.progress.percent)}</p><Composition value={data.annual.team}/>
        <div className={styles.grid}>{(data.target?.levels??[null,null,null]).map((level,i)=><div className={styles.level} key={i}><small>团队第 {i+1} 级 · 年度累计</small><strong>{level===null?"未设置目标":money(level)}</strong>{level!==null&&data.annual.complete&&data.annual.started&&<progress aria-label={`Team level ${i+1} progress`} max={level} value={Math.max(0,Math.min(data.annual.team.total,level))}/>}</div>)}</div>
        <p>当前等级：{data.level.level===null?"未确认":data.level.level===0?"尚未达到第一级":`第 ${data.level.level} 级`} · 下一级差额：{money(data.level.nextGap)}</p>
        <p>未分配业绩 {money(data.annual.unassigned.total)} <Link href={href({tab:"details",employee:"UNASSIGNED",page:"",range:"year"})}>查看明细</Link>。已核对的未分配仍计入团队，不虚构员工。</p>
      </section>
      <section className={styles.card}><h2>{month}月{data.comparison.future?" · 尚未开始":"实收业绩"}</h2><strong className={styles.amountSmall}>{data.comparison.future?"—":money(data.current.team.total)}</strong><p>{data.comparison.label}：{date(data.previous.from)} 至 {date(data.previous.asOf)}</p><p>本期：{data.comparison.future?"尚未开始":`${date(data.current.from)} 至 ${date(new Date(Math.min(now.getTime(),new Date(data.current.toExclusive).getTime()-1)).toISOString())}`}</p><p>{data.comparison.complete?"金额变化":"已核对小计差（不能确认增长）"} {data.comparison.future?"—":money(data.comparison.delta)} · 百分比 {percent(data.comparison.percent)}</p><small>比较基期为零或负数，百分比不适用。</small></section>
      <section className={styles.card}><h2>成员表现</h2>{data.annual.unassignedCount>0&&<p className={styles.warning}>本店仍有未分配收款／退款，个人显示已明确归属金额，暂不确认个人目标完成率。</p>}
        <form method="get" className={styles.filters}><input name="tab" type="hidden" value="overview"/><input name="branch" type="hidden" value={branch.id}/><input name="year" type="hidden" value={year}/><input name="month" type="hidden" value={month}/><label>查找成员<input type="search" aria-label="Find performance member" name="q" defaultValue={p.q??""} placeholder="姓名或员工编号"/></label><button type="submit">查找成员</button></form><div className={styles.memberList}>{data.members.filter(m=>!p.q||`${m.fullName} ${m.employeeCode}`.toLowerCase().includes(p.q.toLowerCase())).map(m=><details key={m.id} className={styles.member}><summary><span><strong>{m.fullName}</strong><small>{m.employeeCode} · {m.status}{!m.eligible?" · 历史本店成员":""}</small></span><span><strong>{money(m.amount.total)}</strong><small>年度目标 {m.goal?money(m.goal):"未设个人目标"}</small></span></summary><p>今年累计完成率 {percent(m.progress.percent)} · 差额 {money(m.progress.gap)}</p><p>{month}月 {data.comparison.future?"尚未开始":money(m.month.total)} · {m.comparison.complete?"比上期":"小计差 / 比较待核对"} {money(m.comparison.delta)}（{percent(m.comparison.percent)}）</p><Composition value={m.amount}/><div className={styles.months}>{m.months.map(mm=><div key={mm.month}><small>{mm.month}月</small><strong>{mm.future?"尚未开始":money(mm.amount.total)}</strong>{!mm.future&&!mm.complete&&<small>归属／数据待补齐</small>}</div>)}</div><Link href={href({tab:"details",employee:m.id,page:""})}>查看本店收款、退款与归属历史 →</Link></details>)}</div>{!data.members.length&&<p>本年度没有成员、个人目标或贡献。团队实收仍独立核查。</p>}
      </section>
    </>}
    {tab==="targets"&&<>{canManage?<TargetEditor key={`${branch.id}:${year}:${data.revision}`} data={data} branchId={branch.id}/>:<section className={styles.card}><h2>年度目标（只读）</h2><p>三级累计门槛：{data.target?.levels.map(money).join(" / ")??"尚未设置"}</p>{data.members.map(m=><p key={m.id}>{m.fullName} · {m.employeeCode}：{m.goal?money(m.goal):"未设个人目标"}</p>)}<p>只有获授权管理员可以修改，不因店长职称或审批权限自动授权。</p></section>}
      <section className={styles.card}><h2>不可变发布历史</h2>{!data.history.length&&<p>尚未发布目标。</p>}{data.history.map(h=><details key={h.id}><summary>版本 {h.revision} · {h.actorName} · {date(h.createdAt)}</summary><p>原因：{h.reason}</p><p>旧门槛：{(h.previousSnapshot as TargetSnapshot|null)?.levels?.map(money).join(" / ")??"初次发布"}</p><p>新门槛：{(h.snapshot as TargetSnapshot).levels.map(money).join(" / ")}</p><p>分配差额 {money((h.snapshot as TargetSnapshot).gap)}</p>{(h.snapshot as TargetSnapshot).people.map(m=><p key={m.membershipId}>{m.fullName} · {m.employeeCode} · {m.status}：{money(m.amount)}</p>)}</details>)}</section></>}
    {tab==="details"&&<section className={styles.card}><h2>收款与退款事件</h2><p>{p.range==="year"?"全年":"本月"}完整已核对汇总 {money(p.range==="year"?data.annual.team.total:data.current.team.total)}，不随分页变化。当前筛选 {data.totalRows} 个来源。</p>{selectedMember&&<p>{selectedMember.fullName} · {selectedMember.employeeCode} · 本店年度贡献 {money(selectedMember.amount.total)} · 年度目标 {selectedMember.goal?money(selectedMember.goal):"未设个人目标"}</p>}
      <form method="get" className={styles.filters}><input name="tab" type="hidden" value="details"/><input name="branch" type="hidden" value={branch.id}/><input name="year" type="hidden" value={year}/><input name="month" type="hidden" value={month}/><label>员工<select name="employee" defaultValue={p.employee??""}><option value="">所有成员与未分配</option><option value="UNASSIGNED">未分配</option>{data.members.map(m=><option key={m.id} value={m.id}>{m.fullName} · {m.employeeCode}</option>)}</select></label><label>明细期间<select name="range" defaultValue={p.range??"month"}><option value="month">选定月份</option><option value="year">全年至统计截止</option></select></label><label>来源状态<select name="status" defaultValue={p.status??""}><option value="">全部状态</option>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>贡献组成<select name="component" defaultValue={p.component??""}><option value="">销售与小费</option><option value="SALE">销售</option><option value="TIP">小费</option></select></label><button type="submit">筛选明细</button></form>
      <div className={styles.events}>{data.details.map(s=><details key={s.sourceKey} className={styles.event}><summary><span><strong>{s.invoiceNumber}</strong><small>{date(s.occurredAt)} · {s.method} · {s.sourceKey.startsWith("REFUND:")?"退款":"来源事件"}</small></span><span><small>本事件团队计入业绩</small><strong>{money(s.qualifiedCents)}</strong><small>{statuses[s.classification]??s.classification}</small></span></summary><dl className={styles.composition}><div><dt>原始金额</dt><dd>{money(s.rawCents)}</dd></div><div><dt>税</dt><dd>{money(s.taxCents)}</dd></div><div><dt>销售</dt><dd>{money(s.salesCents)}</dd></div><div><dt>小费</dt><dd>{money(s.tipCents)}</dd></div></dl><p>组成：{s.compositionStatus} · 原付款 {s.paymentId} · 来源 {s.sourceKey}</p>{s.issues.length?<p className={styles.warning}>{s.issues.join(" / ")}</p>:null}{s.detail?.allocations.map((a,i)=><p key={i}>{a.membershipId?data.members.find(m=>m.id===a.membershipId)?.fullName??a.membershipId:"未分配"} · 销售 {money(a.salesReceived)} · 小费 {money(a.tipsReceived)} · 退款 {money(a.refunds)} · 合计 {money(a.total)}</p>)}<details><summary>查看订单归属版本及更正历史</summary>{s.attributionHistory.map(a=><div key={a.id}><p>{a.component==="TIP"?"小费":"销售"}版本 {a.revision} · {date(a.createdAt)} · {a.reason}</p><small>操作人 {a.actorUserId} · 小费范围付款 {a.paymentId??"整单销售"}</small>{a.shares.map((sh,i)=><p key={i}>{sh.employeeName??"未分配"} · {sh.employeeCode} · {sh.basisPoints/100}%</p>)}</div>)}</details></details>)}</div>
      {!data.details.length&&<p>此期间没有符合筛选条件的来源；不代表其他期间没有交易。</p>}<nav className={styles.tools} aria-label="Performance detail pages">{data.page>1&&<Link href={href({page:String(data.page-1)})}>上一页</Link>}<span>第 {data.page} / {Math.max(1,Math.ceil(data.totalRows/data.pageSize))} 页</span>{data.page*data.pageSize<data.totalRows&&<Link href={href({page:String(data.page+1)})}>下一页</Link>}</nav>
    </section>}
  </main>;
}
