import { randomUUID } from "node:crypto";
import Link from "next/link";
import { notFound } from "next/navigation";
import { GoodsReceiveForm } from "@/components/purchase-order-form";
import { requireBusinessUserForModule } from "@/lib/auth/business-user";
import { canDirectStaff, type BusinessCapability } from "@/lib/business-groups/capabilities";
import { getOperationalBranches } from "@/lib/branches";
import { prisma } from "@/lib/prisma";
import { purchaseOrderTrace } from "@/lib/inventory/supplier-ap-service";
import { approvePurchaseOrderAction, cancelPurchaseOrderAction, closePurchaseOrderAction, receivePurchaseOrderAction, reverseGoodsReceiptLineAction } from "../../purchasing-actions";

export default async function PurchaseOrderDetailPage({ params, searchParams }: { params: Promise<{ purchaseOrderId: string }>; searchParams: Promise<{ message?: string; type?: string }> }) {
  const context = await requireBusinessUserForModule("INVENTORY", "VIEW_PURCHASE_ORDERS"); const { purchaseOrderId } = await params; const query = await searchParams; const branches = await getOperationalBranches(context.businessId, context.user);
  const po = await prisma.purchaseOrder.findFirst({ where: { businessId: context.businessId, branchId: { in: branches.map((branch) => branch.id) }, id: purchaseOrderId }, include: { approvedBy: { select: { name: true } }, branch: true, createdBy: { select: { id: true, name: true } }, supplier: true, lines: { orderBy: { createdAt: "asc" }, include: { product: true } }, receipts: { orderBy: { receivedAt: "desc" }, include: { receivedBy: { select: { name: true } }, lines: { include: { product: true, reversals: true } } } } } }); if (!po) notFound();
  const billingTrace = await purchaseOrderTrace({ businessId: context.businessId, purchaseOrderId: po.id });
  const can = (capability: BusinessCapability) => context.user.role === "BUSINESS_OWNER" || canDirectStaff(context.user.permissions, capability);
  return <section className="content"><div className="page-header"><div><h1>{po.poNumber}</h1><p>{po.supplier.name} · {po.branch.name} · PO creation and approval never change inventory.</p></div><div className="form-actions"><Link href="/inventory/purchase-orders">Purchase orders</Link><Link href={`/inventory/suppliers/${po.supplierId}`}>Supplier</Link>{can("CREATE_SUPPLIER_BILL") ? <Link href={`/inventory/supplier-bills/new?purchaseOrderId=${po.id}`}>Create supplier bill</Link> : null}{po.status === "DRAFT" && can("CREATE_PURCHASE_ORDER") ? <Link className="secondary-link-button" href={`/inventory/purchase-orders/${po.id}/edit`}>Edit draft</Link> : null}</div></div>{query.message ? <p className={`form-message ${query.type === "error" ? "error" : "success"}`}>{query.message}</p> : null}
    <div className="stat-grid"><div className="stat-card"><span>Status</span><strong>{po.status.replaceAll("_", " ")}</strong></div><div className="stat-card"><span>Expected total</span><strong>RM{Number(po.subtotal).toFixed(2)}</strong></div><div className="stat-card"><span>Ordered</span><strong>{po.lines.reduce((sum, line) => sum + line.orderedQuantity, 0)}</strong></div><div className="stat-card"><span>Net received</span><strong>{po.lines.reduce((sum, line) => sum + line.receivedQuantity, 0)}</strong></div><div className="stat-card"><span>Revision</span><strong>{po.revision}</strong></div><div className="stat-card"><span>Receipts</span><strong>{po.receipts.length}</strong></div></div>
    <div className="panel"><div className="section-header"><h2>Order facts</h2><span>{po.currency}</span></div><dl className="detail-list"><div><dt>Supplier</dt><dd>{po.supplier.name}</dd></div><div><dt>Order date</dt><dd>{po.orderDate.toLocaleDateString("en-MY")}</dd></div><div><dt>Expected date</dt><dd>{po.expectedDate?.toLocaleDateString("en-MY") ?? "—"}</dd></div><div><dt>Created by</dt><dd>{po.createdBy.name}</dd></div><div><dt>Approved by</dt><dd>{po.approvedBy?.name ?? "—"}</dd></div><div><dt>Notes</dt><dd>{po.notes ?? "—"}</dd></div></dl><div className="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Ordered</th><th>Net received</th><th>Confirmed billed</th><th>Unbilled received</th><th>Expected cost</th><th>Expected total</th></tr></thead><tbody>{po.lines.map((line) => { const trace = billingTrace.find((item) => item.purchaseOrderLineId === line.id)!; return <tr key={line.id}><td>{line.product.name}</td><td>{line.product.sku ?? "—"}</td><td>{line.orderedQuantity}</td><td>{trace.received}</td><td>{trace.billed}</td><td>{trace.received - trace.billed}</td><td>RM{Number(line.expectedUnitCost).toFixed(2)}</td><td>RM{Number(line.expectedTotal).toFixed(2)}</td></tr>; })}</tbody></table></div></div>
    {po.status === "DRAFT" && can("APPROVE_PURCHASE_ORDER") ? <div className="panel"><h2>Approval</h2>{po.createdById === context.user.userId ? <p className="form-message error">Creator ≠ approver. Ask another authorised user to approve this PO.</p> : <form action={approvePurchaseOrderAction} className="form-actions"><input type="hidden" name="purchaseOrderId" value={po.id} /><input type="hidden" name="expectedRevision" value={po.revision} /><input type="hidden" name="operationKey" value={`APPROVE_PURCHASE_ORDER:${randomUUID()}`} /><button type="submit">Approve PO (stock unchanged)</button></form>}</div> : null}
    {(["APPROVED", "PARTIALLY_RECEIVED"] as string[]).includes(po.status) && can("RECEIVE_PURCHASE_ORDER") ? <div className="panel"><div className="section-header"><h2>Receive goods</h2><span>Writes immutable STOCK_IN movements</span></div><GoodsReceiveForm action={receivePurchaseOrderAction} lines={po.lines.filter((line) => line.receivedQuantity < line.orderedQuantity).map((line) => ({ id: line.id, orderedQuantity: line.orderedQuantity, productName: line.product.name, receivedQuantity: line.receivedQuantity }))} operationKey={`RECEIVE_PURCHASE_ORDER:${randomUUID()}`} purchaseOrderId={po.id} /></div> : null}
    {((po.status === "DRAFT" || po.status === "APPROVED") && po.lines.every((line) => line.receivedQuantity === 0) || po.status === "PARTIALLY_RECEIVED") && can("CANCEL_PURCHASE_ORDER") ? <div className="panel"><h2>{po.status === "PARTIALLY_RECEIVED" ? "Close remaining quantity" : "Cancel or close order"}</h2><div className="form-actions">{po.status !== "PARTIALLY_RECEIVED" ? <form action={cancelPurchaseOrderAction}><input type="hidden" name="purchaseOrderId" value={po.id} /><input type="hidden" name="expectedRevision" value={po.revision} /><input type="hidden" name="operationKey" value={`CANCEL_PURCHASE_ORDER:${randomUUID()}`} /><input name="reason" required minLength={3} placeholder="Cancellation reason" /><button type="submit" className="danger-button">Cancel PO</button></form> : null}{po.status !== "DRAFT" ? <form action={closePurchaseOrderAction}><input type="hidden" name="purchaseOrderId" value={po.id} /><input type="hidden" name="expectedRevision" value={po.revision} /><input type="hidden" name="operationKey" value={`CLOSE_PURCHASE_ORDER:${randomUUID()}`} /><input name="reason" required minLength={3} placeholder="Reason for closing remaining" /><button type="submit" className="secondary-button">Close remaining</button></form> : null}</div></div> : null}
    <div className="panel"><div className="section-header"><h2>Goods receipts</h2><span>Immutable receive notes</span></div>{po.receipts.length ? po.receipts.map((receipt) => <article className="subpanel" key={receipt.id}><div className="section-header"><div><h3>{receipt.receiptNumber}</h3><p>{receipt.receivedAt.toLocaleString("en-MY", { timeZone: "Asia/Kuala_Lumpur" })} · {receipt.receivedBy.name}</p></div><span className={`status ${receipt.status === "RECEIVED" ? "active" : "warning"}`}>{receipt.status.replaceAll("_", " ")}</span></div><p>Delivery reference: {receipt.deliveryReference ?? "—"}</p><div className="table-wrap"><table><thead><tr><th>Product</th><th>Received</th><th>Reversed</th><th>Net</th><th>Action</th></tr></thead><tbody>{receipt.lines.map((line) => { const reversed = line.reversals.reduce((sum, item) => sum + item.reversedQuantity, 0); const net = line.receivedQuantity - reversed; return <tr key={line.id}><td>{line.product.name}</td><td>{line.receivedQuantity}</td><td>{reversed}</td><td>{net}</td><td>{net > 0 && can("REVERSE_GOODS_RECEIPT") ? <form action={reverseGoodsReceiptLineAction} className="inline-form"><input type="hidden" name="goodsReceiptLineId" value={line.id} /><input type="hidden" name="purchaseOrderId" value={po.id} /><input type="hidden" name="operationKey" value={`REVERSE_GOODS_RECEIPT:${randomUUID()}`} /><input name="quantity" type="number" min="1" max={net} defaultValue={net} required /><input name="reason" minLength={3} placeholder="Required reason" required /><button className="danger-button" type="submit">Reverse</button></form> : "—"}</td></tr>; })}</tbody></table></div></article>) : <p className="empty-state">No goods receipts. Inventory is unchanged by this PO.</p>}</div>
  </section>;
}
