import { FINANCIAL_METRIC_DEFINITION_VERSION } from "@/lib/financial-metrics";

export const ANALYTICS_METRIC_DEFINITION_VERSION =
  FINANCIAL_METRIC_DEFINITION_VERSION;
export const ANALYTICS_BUSINESS_DAY_DEFINITION_VERSION = 1;
export const MAX_ANALYTICS_REFRESH_DAYS = 731;
