import { randomUUID } from "node:crypto";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PurchaseOrderForm } from "@/components/purchase-order-form";
import { requireBusinessUserForModule } from "@/lib/auth/business-user";
import { getOperationalBranches } from "@/lib/branches";
import { prisma } from "@/lib/prisma";
import { updatePurchaseOrderAction } from "../../../purchasing-actions";

export default async function EditPurchaseOrderPage({ params, searchParams }: { params: Promise<{ purchaseOrderId: string }>; searchParams: Promise<{ message?: string; type?: string }> }) { const { businessId, user } = await requireBusinessUserForModule("INVENTORY", "CREATE_PURCHASE_ORDER"); const { purchaseOrderId } = await params; const query = await searchParams; const branches = await getOperationalBranches(businessId, user); const po = await prisma.purchaseOrder.findFirst({ where: { businessId, branchId: { in: branches.map((branch) => branch.id) }, id: purchaseOrderId, status: "DRAFT" }, include: { lines: true } }); if (!po) notFound(); const [suppliers, products] = await Promise.all([prisma.supplier.findMany({ where: { businessId, OR: [{ status: "ACTIVE" }, { id: po.supplierId }] }, orderBy: { name: "asc" }, select: { id: true, name: true } }), prisma.product.findMany({ where: { businessId, OR: [{ status: "ACTIVE", trackInventory: true }, { id: { in: po.lines.map((line) => line.productId) } }] }, orderBy: { name: "asc" }, select: { costPrice: true, id: true, name: true, sku: true } })]); return <section className="content"><div className="page-header"><div><h1>Edit {po.poNumber}</h1><p>Draft-only optimistic update. Approval freezes order facts.</p></div><Link href={`/inventory/purchase-orders/${po.id}`}>Back to PO</Link></div>{query.message ? <p className={`form-message ${query.type === "error" ? "error" : "success"}`}>{query.message}</p> : null}<div className="panel"><PurchaseOrderForm action={updatePurchaseOrderAction} branches={branches} expectedRevision={po.revision} initial={{ branchId: po.branchId, expectedDate: po.expectedDate?.toISOString().slice(0, 10), lines: po.lines.map((line) => ({ expectedUnitCost: Number(line.expectedUnitCost), orderedQuantity: line.orderedQuantity, productId: line.productId })), notes: po.notes ?? "", orderDate: po.orderDate.toISOString().slice(0, 10), supplierId: po.supplierId }} operationKey={`UPDATE_PURCHASE_ORDER:${randomUUID()}`} products={products.map((product) => ({ ...product, costPrice: product.costPrice === null ? null : Number(product.costPrice) }))} purchaseOrderId={po.id} submitLabel="Save draft PO" suppliers={suppliers} /></div></section>; }
