import { notFound, redirect } from "next/navigation";
import { AppShellFrame } from "@/components/app-shell-frame";
import { BusinessContextSwitcher } from "@/components/business-context-switcher";
import { createBusinessContextToken } from "@/lib/auth/business-context-token";
import { requireUser } from "@/lib/auth/session";
import { getAvailableGroupReportingContexts } from "@/lib/business-groups/all-stores-access";
import { getAvailableBusinessContexts } from "@/lib/business-groups/business-context";
import { getBusinessGroupNavItems } from "@/lib/business-groups/navigation";
import { formatCents } from "@/lib/commercial/money";
import { getEffectiveCommercialConfiguration } from "@/lib/commercial/service";
import { listSubscriptionInvoices } from "@/lib/commercial/billing-service";

export default async function GroupCommercialPage({ params }: { params: Promise<{ groupId: string }> }) {
  const user = await requireUser(); if (user.role === "PLATFORM_ADMIN") notFound(); if (!user.activeBusinessId) redirect("/business-context/recover");
  const { groupId } = await params; const [groups, businesses] = await Promise.all([getAvailableGroupReportingContexts(user.userId, user.activeBusinessId), getAvailableBusinessContexts(user.userId, user.activeBusinessId)]); const selected = groups.find(group => group.groupId === groupId); if (!selected || selected.role !== "GROUP_OWNER") notFound();
  const commercial = await getEffectiveCommercialConfiguration({ groupId }); const invoices = await listSubscriptionInvoices({ actor: user, groupId }); const token = await createBusinessContextToken({ userId: user.userId, businessId: user.activeBusinessId, contextVersion: user.contextVersion });
  return <AppShellFrame brandName={selected.groupName} homeHref={`/groups/${groupId}/overview`} navItems={getBusinessGroupNavItems(groupId)} businessSwitcher={<BusinessContextSwitcher groups={groups} homeBusiness={businesses.businesses.find(b => b.isHome) ?? null} contextToken={token} selectedGroupId={groupId} />}><section className="content"><div className="page-header"><div><h1>Current group plan</h1><p>Read-only commercial configuration. Group owners cannot change price or allowance.</p></div></div>{commercial.subscription && commercial.allowances ? <div className="grid"><div className="panel metric"><span>Plan</span><strong>{commercial.subscription.items.filter(i => i.status === "ACTIVE").map(i => i.planVersion.plan.displayName).join(" + ")}</strong></div><div className="panel metric"><span>Recurring price</span><strong>{formatCents(commercial.price?.effectiveRecurringPriceCents ?? null)}</strong></div><div className="panel metric"><span>Group Ask Tetamu</span><strong>{commercial.allowances.groupAi} / month</strong></div><div className="panel metric"><span>Renewal</span><strong>{commercial.subscription.renewalDate.toLocaleDateString("en-MY")}</strong></div></div> : <div className="panel"><strong>Legacy / commercial review required</strong><p>Missing historical price is not treated as RM0.</p></div>}<section className="panel"><h2>Group billing history</h2><p>Read-only. No payment or invoice mutation is available to group owners.</p>{invoices.length ? <div className="table-wrap"><table className="table"><thead><tr><th>Invoice</th><th>Period</th><th>Status</th><th>Total</th><th>Outstanding</th></tr></thead><tbody>{invoices.map(invoice => <tr key={invoice.id}><td>{invoice.invoiceNumber}</td><td>{invoice.billingPeriodStart.toLocaleDateString("en-MY")}–{invoice.billingPeriodEnd.toLocaleDateString("en-MY")}</td><td>{invoice.status === "ISSUED" ? invoice.canonicalPaymentStatus : invoice.status}</td><td>{formatCents(invoice.totalAmountCents)}</td><td>{formatCents(invoice.canonicalOutstandingCents)}</td></tr>)}</tbody></table></div> : <p className="empty-state">No group subscription invoices.</p>}</section></section></AppShellFrame>;
}
