ALTER TYPE "WhatsAppMessageStatus" ADD VALUE IF NOT EXISTS 'SENT_TO_SERVER';
ALTER TYPE "WhatsAppMessageStatus" ADD VALUE IF NOT EXISTS 'DELIVERED';
ALTER TYPE "WhatsAppMessageStatus" ADD VALUE IF NOT EXISTS 'READ';

ALTER TYPE "WhatsAppChatMessageStatus" ADD VALUE IF NOT EXISTS 'SENT_TO_SERVER';
ALTER TYPE "WhatsAppChatMessageStatus" ADD VALUE IF NOT EXISTS 'DELIVERED';
ALTER TYPE "WhatsAppChatMessageStatus" ADD VALUE IF NOT EXISTS 'READ';
