import { randomUUID } from "node:crypto";
import Link from "next/link";
import { PurchaseOrderForm } from "@/components/purchase-order-form";
import { requireBusinessUserForModule } from "@/lib/auth/business-user";
import { getOperationalBranches } from "@/lib/branches";
import { prisma } from "@/lib/prisma";
import { createPurchaseOrderAction } from "../../purchasing-actions";

export default async function NewPurchaseOrderPage({ searchParams }: { searchParams: Promise<{ branchId?: string; message?: string; productId?: string; quantity?: string; type?: string }> }) { const { businessId, user } = await requireBusinessUserForModule("INVENTORY", "CREATE_PURCHASE_ORDER"); const query = await searchParams; const [branches, suppliers, products] = await Promise.all([getOperationalBranches(businessId, user), prisma.supplier.findMany({ where: { businessId, status: "ACTIVE" }, orderBy: { name: "asc" }, select: { id: true, name: true } }), prisma.product.findMany({ where: { businessId, status: "ACTIVE", trackInventory: true }, orderBy: { name: "asc" }, select: { costPrice: true, id: true, name: true, sku: true } })]); const quantity = Number(query.quantity); const prefill = branches.some((branch) => branch.id === query.branchId) && products.some((product) => product.id === query.productId) && Number.isInteger(quantity) && quantity > 0 ? { branchId: query.branchId!, productId: query.productId!, quantity } : undefined; return <section className="content"><div className="page-header"><div><h1>New purchase order</h1><p>Creates a draft commercial intent only. Inventory remains unchanged.</p></div><Link href="/inventory/purchase-orders">Back to purchase orders</Link></div>{query.message ? <p className={`form-message ${query.type === "error" ? "error" : "success"}`}>{query.message}</p> : null}{prefill ? <p className="form-message success">Reorder suggestion prefilled. Select the supplier and review quantity before saving.</p> : null}<div className="panel">{!suppliers.length ? <p className="form-message error">Create an active supplier first.</p> : null}{!products.length ? <p className="form-message error">No active inventory-tracked products are available.</p> : null}<PurchaseOrderForm action={createPurchaseOrderAction} branches={branches} operationKey={`CREATE_PURCHASE_ORDER:${randomUUID()}`} prefill={prefill} suppliers={suppliers} products={products.map((product) => ({ ...product, costPrice: product.costPrice === null ? null : Number(product.costPrice) }))} /></div></section>; }
