import { randomUUID } from "node:crypto";
import Link from "next/link";
import { notFound } from "next/navigation";
import { requireBusinessUserForModule } from "@/lib/auth/business-user";
import { hasBusinessCapability } from "@/lib/business-groups/business-access";
import { resolveExpenseReadScope } from "@/lib/expense/access";
import { getBusinessExpenseDetail } from "@/lib/expense/service";
import { loadBusinessModuleContext } from "@/lib/modules/entitlements";
import { confirmExpenseAction, markExpensePaidAction, voidExpenseAction } from "../actions";
import styles from "../expense.module.css";

export default async function ExpenseDetailPage({ params, searchParams }: { params: Promise<{ expenseId: string }>; searchParams: Promise<{ message?: string; type?: string }> }) {
  const context = await requireBusinessUserForModule("EXPENSE", "VIEW_EXPENSE");
  const [{ expenseId }, query, scope, moduleContext] = await Promise.all([params, searchParams, resolveExpenseReadScope(context), loadBusinessModuleContext(context.businessId)]);
  const expense = await getBusinessExpenseDetail({ businessId: context.businessId, expenseId, ...scope }).catch(() => null);
  if (!expense) notFound();
  const canEdit = hasBusinessCapability(context.access, "EDIT_EXPENSE_DRAFT") && expense.sourceType === "MANUAL" && expense.status !== "VOID" && expense.paymentStatus !== "PAID";
  const canConfirm = hasBusinessCapability(context.access, "CONFIRM_EXPENSE") && expense.sourceType === "MANUAL" && expense.status === "DRAFT";
  const canMarkPaid = hasBusinessCapability(context.access, "MARK_EXPENSE_PAID") && expense.sourceType === "MANUAL" && expense.status === "CONFIRMED" && expense.paymentStatus === "UNPAID";
  const canVoid = hasBusinessCapability(context.access, "VOID_EXPENSE") && expense.sourceType === "MANUAL" && expense.status === "CONFIRMED" && expense.paymentStatus === "UNPAID";
  const canViewReceipt = hasBusinessCapability(context.access, "VIEW_EXPENSE_RECEIPT");
  const sourceHref = expense.sourceSnapshot && expense.sourceType === "CLAIM" && hasBusinessCapability(context.access, "VIEW_CLAIM") ? `/team/claims?claimId=${expense.sourceSnapshot.sourceRecordId}` : expense.sourceSnapshot && expense.sourceType === "PAYROLL" && hasBusinessCapability(context.access, "VIEW_PAYROLL_RUN") ? `/team/payroll/runs/${expense.sourceSnapshot.sourceRecordId}` : expense.sourceSnapshot && expense.sourceType === "INVENTORY_PURCHASE" && moduleContext.enabledModules.has("INVENTORY") && hasBusinessCapability(context.access, "VIEW_SUPPLIER_BILL") ? `/inventory/supplier-bills/${expense.sourceSnapshot.sourceRecordId}` : null;
  return <section className="content"><div className="page-header"><div><h1>{expense.expenseNumber}</h1><p>{expense.status} · {expense.paymentStatus} · revision {expense.revision}</p></div><div className="form-actions"><Link href="/expenses/history">Expense history</Link>{canEdit ? <Link href={`/expenses/${expense.id}/edit`}>Edit / Correct</Link> : null}</div></div>
    {query.message ? <p className={`form-message ${query.type === "error" ? "error" : "success"}`}>{query.message}</p> : null}
    <div className={styles.facts}><Fact label="Recorded amount" value={`RM ${expense.amount.toFixed(2)}`} />{expense.sourceSettlement ? <><Fact label="Paid amount" value={`RM ${expense.sourceSettlement.paidAmount.toFixed(2)}`} /><Fact label="Outstanding" value={`RM ${expense.sourceSettlement.outstandingAmount.toFixed(2)}`} /><Fact label="Settlement" value={expense.sourceSettlement.settlementStatus.replaceAll("_", " ")} /></> : <Fact label="Payment Date" value={expense.paymentDate ? formatDate(expense.paymentDate) : "Not paid"} />}<Fact label="Expense Date" value={formatDate(expense.expenseDate)} /><Fact label="Category" value={expense.categoryNameSnapshot} /><Fact label="Branch" value={expense.branchNameSnapshot ?? "Business-wide"} /><Fact label="Payee" value={expense.payeeName ?? "—"} /></div>
    <div className={styles.grid}><div className="panel"><h2>Expense facts</h2><dl><dt>Description</dt><dd>{expense.description}</dd><dt>Notes</dt><dd>{expense.notes ?? "—"}</dd><dt>Created by</dt><dd>{expense.createdBy.name}</dd><dt>Confirmed by</dt><dd>{expense.confirmedBy?.name ?? "—"}</dd>{expense.status === "VOID" ? <><dt>Void reason</dt><dd>{expense.voidReason}</dd></> : null}</dl></div><div className="panel"><h2>Payment information</h2><dl><dt>Status</dt><dd>{expense.paymentStatus}</dd><dt>Method</dt><dd>{expense.paymentMethod?.replaceAll("_", " ") ?? "—"}</dd><dt>Reference</dt><dd>{expense.paymentReference ?? "—"}</dd><dt>Marked paid by</dt><dd>{expense.paidBy?.name ?? "—"}</dd></dl></div></div>
    <div className="panel"><h2>Receipt / Attachment</h2>{expense.attachments.length ? expense.attachments.map((attachment) => { const releasable = attachment.malwareStatus === "CLEAN" && ["SAFE", "SANITIZED"].includes(attachment.privacyMetadataStatus); return <div key={attachment.id}><strong>{attachment.sanitizedFileName}</strong> · {(attachment.byteLength / 1024).toFixed(1)} KB · Malware {attachment.malwareStatus} · Privacy {attachment.privacyMetadataStatus}{canViewReceipt && releasable ? <> · <a href={`/api/expenses/attachments/${attachment.id}`} target="_blank" rel="noreferrer">View receipt</a></> : <p className={styles.notice}>Private receipt remains quarantined. MALWARE_SCANNER_NOT_CONFIGURED or privacy review is pending.</p>}</div>; }) : <p>No receipt attached.</p>}</div>
    <div className="panel"><h2>Source identity</h2><p>{expense.sourceType !== "MANUAL" ? <strong>System Generated · Read-only · </strong> : null}Source: {expense.sourceType === "MANUAL" ? "Manual Entry" : expense.sourceType === "INVENTORY_PURCHASE" ? "Supplier Bill" : expense.sourceType.replaceAll("_", " ")}</p><p className={styles.source}>Source ID: {expense.sourceId ?? "—"}<br />Source revision: {expense.sourceRevision ?? "—"}</p>{expense.sourceSnapshot ? <dl><dt>Canonical record</dt><dd>{expense.sourceSnapshot.sourceNumberSnapshot}</dd><dt>Recognition status</dt><dd>{expense.sourceSnapshot.sourceStatusSnapshot}</dd><dt>Source digest</dt><dd className={styles.source}>{expense.sourceSnapshot.sourceDigest}</dd>{expense.sourceType === "CLAIM" ? <><dt>Submitted / approved</dt><dd>RM {expense.sourceSnapshot.submittedAmount?.toFixed(2) ?? "0.00"} / RM {expense.sourceSnapshot.approvedAmount?.toFixed(2) ?? "0.00"}</dd><dt>Source receipt</dt><dd>{expense.sourceSnapshot.receiptAvailable ? "Available in Claims (not copied)" : "No source receipt"}</dd></> : null}{expense.sourceType === "PAYROLL" ? <><dt>Gross remuneration</dt><dd>RM {expense.sourceSnapshot.grossRemuneration?.toFixed(2) ?? "0.00"}</dd><dt>Employer contributions</dt><dd>RM {expense.sourceSnapshot.employerContributionTotal?.toFixed(2) ?? "0.00"}</dd><dt>Excluded pass-through</dt><dd>RM {expense.sourceSnapshot.excludedPassThrough?.toFixed(2) ?? "0.00"}</dd></> : null}</dl> : null}{sourceHref ? <p><Link href={sourceHref}>Open canonical source</Link></p> : null}{expense.sourceType !== "MANUAL" ? <p>Read-only representation. Amount, payment and lifecycle must be changed in the canonical source domain.</p> : null}</div>
    {(canConfirm || canMarkPaid || canVoid) ? <div className="panel"><h2>Actions</h2><div className={styles.grid}>{canConfirm ? <form action={confirmExpenseAction} className={styles.actions}><input type="hidden" name="expenseId" value={expense.id} /><input type="hidden" name="expectedRevision" value={expense.revision} /><input type="hidden" name="operationKey" value={`CONFIRM_EXPENSE:${expense.id}:${randomUUID()}`} /><button>Confirm Expense</button></form> : null}{canMarkPaid ? <form action={markExpensePaidAction} className={styles.form}><input type="hidden" name="expenseId" value={expense.id} /><input type="hidden" name="expectedRevision" value={expense.revision} /><input type="hidden" name="operationKey" value={`MARK_EXPENSE_PAID:${expense.id}:${randomUUID()}`} /><label>Payment Date<input name="paymentDate" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} /></label><label>Method<select name="paymentMethod" required><option value="BANK_TRANSFER">Bank Transfer</option><option value="CASH">Cash</option><option value="CARD">Card</option><option value="EWALLET">E-wallet</option><option value="OTHER">Other</option></select></label><label className={styles.full}>Reference<input name="paymentReference" maxLength={160} /></label><button className={styles.full}>Mark Paid</button></form> : null}{canVoid ? <form action={voidExpenseAction} className={styles.form}><input type="hidden" name="expenseId" value={expense.id} /><input type="hidden" name="expectedRevision" value={expense.revision} /><input type="hidden" name="operationKey" value={`VOID_EXPENSE:${expense.id}:${randomUUID()}`} /><label className={styles.full}>Void reason<input name="reason" required minLength={5} maxLength={500} /></label><button className={`danger-button ${styles.full}`}>Void unpaid Expense</button></form> : null}</div></div> : null}
    <div className="panel"><h2>Immutable revision history</h2><div className={styles.stack}>{expense.revisions.map((revision) => <div className={styles.history} key={revision.id}><strong>Revision {revision.revision} · {revision.revisionType}</strong><div>{formatDateTime(revision.createdAt)} · {revision.createdBy.name} · RM {revision.amount.toFixed(2)} · {revision.status} / {revision.paymentStatus}</div>{revision.reason ? <div>{revision.reason}</div> : null}</div>)}</div></div>
  </section>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div className={styles.fact}><span>{label}</span><strong>{value}</strong></div>; }
function formatDate(value: Date) { return value.toLocaleDateString("en-MY", { timeZone: "Asia/Kuala_Lumpur" }); }
function formatDateTime(value: Date) { return value.toLocaleString("en-MY", { timeZone: "Asia/Kuala_Lumpur" }); }
