import { randomUUID } from "node:crypto";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PayrollHighRiskMfaFields } from "@/components/payroll-high-risk-mfa-fields";
import { requireBusinessUserForModule } from "@/lib/auth/business-user";
import { hasBusinessCapability } from "@/lib/business-groups/business-access";
import type { BusinessCapability } from "@/lib/business-groups/capabilities";
import { getOperationalBranches } from "@/lib/branches";
import { getSupplierBillDetail } from "@/lib/inventory/supplier-ap-service";
import { prisma } from "@/lib/prisma";
import { attachSupplierInvoiceAction, confirmSupplierBillAction, recordSupplierPaymentAction, reverseSupplierPaymentAction, updateSupplierBillAction, voidSupplierBillAction } from "../../supplier-ap-actions";

export default async function SupplierBillDetailPage({ params, searchParams }: { params: Promise<{ billId: string }>; searchParams: Promise<{ message?: string; type?: string }> }) {
  const context = await requireBusinessUserForModule("INVENTORY", "VIEW_SUPPLIER_BILL");
  const [{ billId }, query, branches] = await Promise.all([params, searchParams, getOperationalBranches(context.businessId, context.user)]);
  let bill: Awaited<ReturnType<typeof getSupplierBillDetail>>;
  try { bill = await getSupplierBillDetail({ businessId: context.businessId, billId, allowedBranchIds: branches.map((branch) => branch.id) }); } catch { notFound(); }
  const can = (capability: BusinessCapability) => hasBusinessCapability(context.access, capability);
  const expenseRepresentation = hasBusinessCapability(context.access, "VIEW_EXPENSE") ? await prisma.businessExpense.findFirst({ where: { businessId: context.businessId, sourceType: "INVENTORY_PURCHASE", sourceId: bill.id }, orderBy: { createdAt: "desc" }, select: { id: true, status: true } }) : null;
  const priceVariance = bill.lines.some((line) => !line.unitPrice.equals(line.purchaseOrderLine.expectedUnitCost));
  return <section className="content">
    <div className="page-header"><div><h1>{bill.billNumber}</h1><p>{bill.supplier.name} · Invoice {bill.supplierInvoiceNumber} · Bill and payment never change inventory.</p></div><div className="form-actions"><Link href="/inventory/supplier-bills">Supplier bills</Link><Link href="/inventory/accounts-payable">Accounts payable</Link><Link href={`/inventory/purchase-orders/${bill.purchaseOrderId}`}>{bill.purchaseOrder.poNumber}</Link></div></div>
    {query.message ? <p className={`form-message ${query.type === "error" ? "error" : "success"}`}>{query.message}</p> : null}
    <div className="stat-grid"><div className="stat-card"><span>Bill status</span><strong>{bill.status}</strong></div><div className="stat-card"><span>Matching</span><strong>{bill.matchStatus.replaceAll("_", " ")}</strong></div><div className="stat-card"><span>Total</span><strong>RM{bill.totalAmount.toFixed(2)}</strong></div><div className="stat-card"><span>Valid paid</span><strong>RM{bill.validPaidAmount.toFixed(2)}</strong></div><div className="stat-card"><span>Outstanding</span><strong>RM{bill.outstandingAmount.toFixed(2)}</strong></div><div className="stat-card"><span>Payment status</span><strong>{bill.status === "CONFIRMED" ? bill.derivedPaymentStatus.replaceAll("_", " ") : "NOT AP"}</strong></div></div>
    {expenseRepresentation ? <div className="panel"><strong>{expenseRepresentation.status === "CONFIRMED" ? "Included in Recorded Business Spending" : "Historical Business Spending representation"}</strong><p>Supplier Bill remains canonical. Supplier Payment only settles AP and never creates another Expense.</p><Link href={`/expenses/${expenseRepresentation.id}`}>Open read-only Expense representation</Link></div> : bill.status === "CONFIRMED" ? <div className="panel"><strong>Expense materialization pending reconciliation</strong><p>AP remains valid; Expense integration never rolls back Supplier Bill confirmation.</p></div> : null}
    <div className="panel"><div className="section-header"><h2>Canonical bill facts</h2><span>Revision {bill.revision}</span></div><dl className="detail-list"><div><dt>Supplier invoice</dt><dd>{bill.supplierInvoiceNumber}</dd></div><div><dt>Invoice date</dt><dd>{bill.invoiceDate.toLocaleDateString("en-MY")}</dd></div><div><dt>Due date</dt><dd>{bill.dueDate.toLocaleDateString("en-MY")}</dd></div><div><dt>Created by</dt><dd>{bill.createdBy.name}</dd></div><div><dt>Confirmed by</dt><dd>{bill.confirmedBy?.name ?? "—"}</dd></div><div><dt>Notes</dt><dd>{bill.notes ?? "—"}</dd></div></dl>
      <div className="table-wrap"><table><thead><tr><th>Product</th><th>Ordered</th><th>Net received at confirm</th><th>Previously billed</th><th>This bill</th><th>Expected price</th><th>Bill price</th><th>Total</th></tr></thead><tbody>{bill.lines.map((line) => <tr key={line.id}><td>{line.descriptionSnapshot}</td><td>{line.orderedQuantitySnapshot}</td><td>{line.netReceivedSnapshot}</td><td>{line.previouslyBilledSnapshot}</td><td>{line.billedQuantity}</td><td>RM{line.purchaseOrderLine.expectedUnitCost.toFixed(2)}</td><td>{!line.unitPrice.equals(line.purchaseOrderLine.expectedUnitCost) ? <strong>RM{line.unitPrice.toFixed(2)} · VARIANCE</strong> : `RM${line.unitPrice.toFixed(2)}`}</td><td>RM{line.lineTotal.toFixed(2)}</td></tr>)}</tbody></table></div>
    </div>
    <div className="panel"><div className="section-header"><h2>Ordered / received / billed trace</h2><span>Net received includes receipt reversals</span></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>Ordered</th><th>Net received now</th><th>Confirmed billed now</th><th>Unbilled received</th></tr></thead><tbody>{bill.trace.map((line) => <tr key={line.purchaseOrderLineId}><td>{line.productName}</td><td>{line.ordered}</td><td>{line.received}</td><td>{line.billed}</td><td>{line.received - line.billed}</td></tr>)}</tbody></table></div>{bill.trace.some((line) => line.billed > line.received) ? <p className="form-message error">Reconciliation issue: a later Goods Receipt reversal has made confirmed billed quantity exceed net received quantity. The historical bill remains immutable.</p> : null}</div>
    <div className="panel"><div className="section-header"><h2>Supplier invoice attachment</h2><span>Private quarantine · MIME and SHA-256 verified</span></div>{bill.attachment ? <dl className="detail-list"><div><dt>File</dt><dd>{bill.attachment.sanitizedFileName}</dd></div><div><dt>Type</dt><dd>{bill.attachment.mimeType}</dd></div><div><dt>Size</dt><dd>{bill.attachment.byteLength} bytes</dd></div><div><dt>SHA-256</dt><dd className="mono">{bill.attachment.checksumSha256}</dd></div><div><dt>Security state</dt><dd>{bill.attachment.malwareStatus} · {bill.attachment.privacyMetadataStatus}</dd></div></dl> : bill.status === "DRAFT" && can("EDIT_SUPPLIER_BILL_DRAFT") ? <form action={attachSupplierInvoiceAction} className="inline-form"><input type="hidden" name="billId" value={bill.id} /><input type="hidden" name="operationKey" value={`ATTACH_SUPPLIER_INVOICE:${randomUUID()}`} /><input type="file" name="invoiceAttachment" accept="application/pdf,image/jpeg,image/png,image/webp" required /><button type="submit">Upload private attachment</button></form> : <p className="empty-state">No supplier invoice attachment.</p>}</div>
    {bill.status === "DRAFT" && can("EDIT_SUPPLIER_BILL_DRAFT") ? <div className="panel"><div className="section-header"><h2>Edit draft</h2><span>Still no AP effect</span></div><form action={updateSupplierBillAction} className="stacked-form"><input type="hidden" name="billId" value={bill.id} /><input type="hidden" name="expectedRevision" value={bill.revision} /><input type="hidden" name="operationKey" value={`UPDATE_SUPPLIER_BILL:${randomUUID()}`} /><div className="form-grid"><label><span>Supplier invoice number</span><input name="supplierInvoiceNumber" defaultValue={bill.supplierInvoiceNumber} maxLength={120} required /></label><label><span>Invoice date</span><input name="invoiceDate" type="date" defaultValue={bill.invoiceDate.toISOString().slice(0, 10)} required /></label><label><span>Due date</span><input name="dueDate" type="date" defaultValue={bill.dueDate.toISOString().slice(0, 10)} required /></label><label><span>Notes</span><input name="notes" defaultValue={bill.notes ?? ""} maxLength={2000} /></label></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>Quantity</th><th>Unit price (MYR)</th></tr></thead><tbody>{bill.lines.map((line) => <tr key={line.id}><td>{line.descriptionSnapshot}<input type="hidden" name="purchaseOrderLineId" value={line.purchaseOrderLineId} /></td><td><input name="billedQuantity" type="number" min="1" defaultValue={line.billedQuantity} required /></td><td><input name="unitPrice" inputMode="decimal" pattern="\d+(\.\d{1,2})?" defaultValue={line.unitPrice.toFixed(2)} required /></td></tr>)}</tbody></table></div><button type="submit">Update draft</button></form></div> : null}
    {bill.status === "DRAFT" && can("CONFIRM_SUPPLIER_BILL") ? <div className="panel"><div className="section-header"><h2>Confirm supplier bill</h2><span>Creates AP and Inventory Purchase spending · stock unchanged</span></div><form action={confirmSupplierBillAction} className="stacked-form"><input type="hidden" name="billId" value={bill.id} /><input type="hidden" name="expectedRevision" value={bill.revision} /><input type="hidden" name="operationKey" value={`CONFIRM_SUPPLIER_BILL:${randomUUID()}`} />{priceVariance ? <><label className="checkbox-row"><input type="checkbox" name="priceVarianceAcknowledged" required />I reviewed and accept the price variance shown above.</label><label><span>Price variance reason</span><textarea name="priceVarianceReason" minLength={3} maxLength={500} required /></label></> : null}<button type="submit">Confirm bill · AP RM{bill.totalAmount.toFixed(2)}</button></form></div> : null}
    {bill.status === "CONFIRMED" && bill.outstandingAmount.greaterThan(0) && can("RECORD_SUPPLIER_PAYMENT") ? <div className="panel"><div className="section-header"><h2>Record supplier payment</h2><span>Canonical outstanding RM{bill.outstandingAmount.toFixed(2)}</span></div><form action={recordSupplierPaymentAction} className="stacked-form"><input type="hidden" name="billId" value={bill.id} /><input type="hidden" name="operationKey" value={`RECORD_SUPPLIER_PAYMENT:${randomUUID()}`} /><div className="form-grid"><label><span>Amount (MYR)</span><input name="amount" inputMode="decimal" pattern="\d+(\.\d{1,2})?" defaultValue={bill.outstandingAmount.toFixed(2)} required /></label><label><span>Payment date</span><input name="paymentDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label><label><span>Method</span><select name="paymentMethod" defaultValue="BANK_TRANSFER"><option value="BANK_TRANSFER">Bank transfer</option><option value="CASH">Cash</option><option value="CARD">Card</option><option value="EWALLET">E-wallet</option><option value="CHEQUE">Cheque</option><option value="OTHER">Other</option></select></label><label><span>Reference</span><input name="paymentReference" maxLength={160} /></label></div><label><span>Notes</span><textarea name="notes" maxLength={2000} /></label><PayrollHighRiskMfaFields actionLabel="record supplier payment" /><button type="submit">Complete supplier payment</button></form></div> : null}
    <div className="panel"><div className="section-header"><h2>Supplier payments</h2><span>Completed payments are immutable</span></div>{bill.payments.length ? <div className="table-wrap"><table><thead><tr><th>Payment</th><th>Date</th><th>Amount</th><th>Method</th><th>Status</th><th>Reference</th><th>Action</th></tr></thead><tbody>{bill.payments.map((payment) => <tr key={payment.id}><td>{payment.paymentNumber}</td><td>{payment.paymentDate.toLocaleDateString("en-MY")}</td><td>RM{payment.amount.toFixed(2)}</td><td>{payment.paymentMethod.replaceAll("_", " ")}</td><td>{payment.status}</td><td>{payment.paymentReference ?? "—"}</td><td>{payment.status === "COMPLETED" && can("REVERSE_SUPPLIER_PAYMENT") ? <details><summary>Reverse</summary><form action={reverseSupplierPaymentAction} className="stacked-form"><input type="hidden" name="billId" value={bill.id} /><input type="hidden" name="paymentId" value={payment.id} /><input type="hidden" name="operationKey" value={`REVERSE_SUPPLIER_PAYMENT:${randomUUID()}`} /><label><span>Required reason</span><input name="reason" minLength={3} maxLength={500} required /></label><PayrollHighRiskMfaFields actionLabel="reverse supplier payment" /><button className="danger-button" type="submit">Create reversal</button></form></details> : payment.reversal ? `Reversed: ${payment.reversal.reason}` : "—"}</td></tr>)}</tbody></table></div> : <p className="empty-state">No supplier payments.</p>}</div>
    {bill.status === "CONFIRMED" && bill.validPaidAmount.isZero() && can("VOID_SUPPLIER_BILL") ? <div className="panel"><h2>Void supplier bill</h2><form action={voidSupplierBillAction} className="inline-form"><input type="hidden" name="billId" value={bill.id} /><input type="hidden" name="expectedRevision" value={bill.revision} /><input type="hidden" name="operationKey" value={`VOID_SUPPLIER_BILL:${randomUUID()}`} /><input name="reason" minLength={3} maxLength={500} placeholder="Required reason" required /><button className="danger-button" type="submit">Void unpaid bill</button></form></div> : null}
  </section>;
}
