import { randomUUID } from "node:crypto";
import Link from "next/link";
import { notFound } from "next/navigation";
import { sanitizePayrollNotice } from "@/lib/payroll/error-message";
import { resolvePaymentReadAccess } from "@/lib/payroll/payment/payment-access";
import {
  loadPaymentBatchDetail,
  parseInstructionBlocker,
  parseInstructionSearch,
  parseInstructionStatus,
  parsePaymentPage,
  paymentInstructionBlockers,
  paymentInstructionStatuses,
} from "@/lib/payroll/payment/payment-read";
import { approvePaymentBatchAction, cancelPaymentBatchAction, createCorrectionPaymentBatchAction, submitPaymentBatchAction } from "../actions";
import { PaymentAccessDenied, PaymentPageHeader, PaymentStatusBadge, blockerLabel, formatPaymentDate, formatPaymentMoney, formatPaymentMonth, instructionStatusLabel } from "../_components";
import styles from "../payments.module.css";

export const dynamic = "force-dynamic";

type DetailQuery = { blocker?: string; message?: string; page?: string; q?: string; status?: string; type?: string };

export default async function PaymentBatchDetailPage({ params, searchParams }: { params: Promise<{ batchId: string }>; searchParams: Promise<DetailQuery> }) {
  const access = await resolvePaymentReadAccess();
  if (!access.granted) return <PaymentAccessDenied scopeRestricted={access.scopeRestricted} />;
  const [{ batchId }, query] = await Promise.all([params, searchParams]);
  const filters = {
    blocker: parseInstructionBlocker(query.blocker),
    query: parseInstructionSearch(query.q),
    status: parseInstructionStatus(query.status),
  };
  const data = await loadPaymentBatchDetail(access.businessId, batchId, parsePaymentPage(query.page), access.actions.canViewAudit, filters);
  if (!data) notFound();
  const { batch } = data;
  const notice = sanitizePayrollNotice(query.message, query.type);
  const makerBlocked = batch.createdById === access.userId;

  return <main className={`content hr-module-page ${styles.page}`}>
    <PaymentPageHeader title={batch.batchNumber} description="Immutable employee payment instructions captured from a finalized Payroll Run."><Link href="/team/payroll/payments">All batches</Link><Link href={`/team/payroll/runs/${batch.payrollRunId}`}>Payroll Run</Link></PaymentPageHeader>
    {notice ? <div className={`${styles.notice} ${query.type === "error" ? styles.noticeError : ""}`} role={query.type === "error" ? "alert" : "status"}>{notice}</div> : null}
    <section className={styles.hero}><div><p className={styles.eyebrow}>{formatPaymentMonth(batch.payrollRun.periodStart)} · {batch.batchType === "CORRECTION" ? "Correction" : "Original"} revision {batch.revision}</p><h2><PaymentStatusBadge status={batch.status} /></h2><p>{statusTruth(batch.status)}</p></div><div className={styles.metrics}><div className={styles.metric}><span>Ready</span><strong>{batch.readyCount}</strong></div><div className={styles.metric}><span>Blocked</span><strong>{batch.blockedCount}</strong></div><div className={styles.metric}><span>Ready amount</span><strong>{formatPaymentMoney(batch.totalReadyAmount)}</strong></div></div></section>
    <section className={styles.panel}><div className={styles.sectionHeading}><div><h2>Workflow actions</h2><p>Approval is maker-checker controlled. No action here sends money to a bank.</p></div></div><div className={styles.actionZone}>
      {batch.status === "DRAFT" && access.actions.canSubmit ? <ActionCard title="Submit for approval"><form className={styles.reasonForm} action={submitPaymentBatchAction}>{fields(batch.id, batch.revision, "PAYMENT_BATCH_SUBMIT")}<label>Submission reason<textarea name="reason" minLength={5} maxLength={500} required /></label><button className={styles.primaryButton} type="submit">Submit for approval</button></form></ActionCard> : null}
      {batch.status === "AWAITING_APPROVAL" && access.actions.canApprove ? <ActionCard title="Independent approval">{makerBlocked ? <div className={styles.noticeError}>The batch creator cannot approve the same batch. A different authorized user must review it.</div> : <form className={styles.reasonForm} action={approvePaymentBatchAction}>{fields(batch.id, batch.revision, "PAYMENT_BATCH_APPROVE")}<label>Approval reason<textarea name="reason" minLength={5} maxLength={500} required /></label><button className={styles.primaryButton} type="submit">Approve instructions</button></form>}</ActionCard> : null}
      {(["DRAFT", "AWAITING_APPROVAL"] as string[]).includes(batch.status) && access.actions.canCancel ? <ActionCard highRisk title="Cancel batch"><form className={styles.reasonForm} action={cancelPaymentBatchAction}>{fields(batch.id, batch.revision, "PAYMENT_BATCH_CANCEL")}<label>Cancellation reason<textarea name="reason" minLength={5} maxLength={500} required /></label><button className={styles.dangerButton} type="submit">Cancel batch</button></form></ActionCard> : null}
      {batch.status === "CANCELLED" && access.actions.canCreate && !batch.supersededById ? <ActionCard title="Create correction"><form className={styles.reasonForm} action={createCorrectionPaymentBatchAction}><input type="hidden" name="commandId" value={randomUUID()} /><input type="hidden" name="expectedRevision" value={batch.revision} /><input type="hidden" name="supersedesBatchId" value={batch.id} /><input type="hidden" name="reasonType" value="PAYMENT_BATCH_CORRECTION" /><label>Correction reason<textarea name="reason" minLength={5} maxLength={500} required /></label><button className={styles.primaryButton} type="submit">Create correction draft</button></form></ActionCard> : null}
      {!hasAction(batch.status, access.actions) ? <div className={styles.empty}><strong>No workflow action available</strong><p>Your capability or this batch state does not allow a change.</p></div> : null}
    </div></section>
    <section className={styles.panel}><div className={styles.sectionHeading}><div><h2>Payment instructions</h2><p>{data.totalInstructions} matching immutable employee snapshots. Full bank account numbers are never returned to this page.</p></div></div><InstructionFilters batchId={batch.id} filters={filters} /><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Employee</th><th>Net pay</th><th>Bank snapshot</th><th>Status</th><th>Finding</th><th>Reference</th></tr></thead><tbody>{data.instructions.map((item) => <tr key={item.id}><td data-label="Employee">{access.canViewEmployeeProfile ? <Link href={`/team/people/${item.employeeMembershipId}?section=payroll`}><strong>{item.employeeNameSnapshot}</strong></Link> : <strong>{item.employeeNameSnapshot}</strong>}<small>{item.employeeCodeSnapshot}</small></td><td data-label="Net pay">{formatPaymentMoney(item.netPaySnapshot)}</td><td data-label="Bank snapshot">{item.bankNameSnapshot ? <><span>{item.bankNameSnapshot}</span><small className={styles.account}>•••• {item.accountNumberLast4Snapshot}</small></> : "Not captured"}</td><td data-label="Status"><span className={styles.badge}>{instructionStatusLabel(item.status)}</span></td><td data-label="Finding">{blockerLabel(item.blockerCode)}</td><td data-label="Reference"><small>{item.reference}</small></td></tr>)}</tbody></table></div>{data.instructions.length ? <Pagination batchId={batch.id} filters={filters} page={data.page} totalPages={data.totalPages} /> : <div className={styles.empty}><strong>No matching payment instructions</strong><p>Change or clear the search and filters to see other employee snapshots.</p></div>}</section>
    <section className={styles.panel}><div className={styles.sectionHeading}><div><h2>Batch record</h2><p>Approval is not payment completion.</p></div></div><dl className={styles.metrics}><div className={styles.metric}><span>Created by</span><strong>{batch.createdBy.name}</strong><small>{formatPaymentDate(batch.createdAt)}</small></div><div className={styles.metric}><span>Submitted by</span><strong>{batch.submittedBy?.name ?? "Not submitted"}</strong><small>{formatPaymentDate(batch.submittedAt)}</small></div><div className={styles.metric}><span>Approved by</span><strong>{batch.approvedBy?.name ?? "Not approved"}</strong><small>{formatPaymentDate(batch.approvedAt)}</small></div></dl>{batch.reasonSafe ? <p className={styles.batchMeta}>Recorded reason: {batch.reasonSafe}</p> : null}</section>
    {access.actions.canViewAudit ? <section className={styles.panel}><div className={styles.sectionHeading}><div><h2>Payment audit trail</h2><p>Safe append-only workflow events; no full bank account data.</p></div></div><div className={styles.timeline}>{data.events.map((event) => <div className={styles.event} key={event.id}><strong>{event.action.replaceAll("_", " ")}</strong><span>{event.actor.name}</span><small>{formatPaymentDate(event.createdAt)}{event.reasonSafe ? ` · ${event.reasonSafe}` : ""}</small></div>)}</div></section> : null}
  </main>;
}

function ActionCard({ children, highRisk = false, title }: { children: React.ReactNode; highRisk?: boolean; title: string }) { return <details className={`${styles.actionCard} ${highRisk ? styles.highRisk : ""}`}><summary>{title}</summary>{children}</details>; }
function fields(batchId: string, revision: number, reasonType: string) { return <><input type="hidden" name="commandId" value={randomUUID()} /><input type="hidden" name="expectedRevision" value={revision} /><input type="hidden" name="paymentBatchId" value={batchId} /><input type="hidden" name="reasonType" value={reasonType} /></>; }
function hasAction(status: string, actions: { canApprove: boolean; canCancel: boolean; canCreate: boolean; canSubmit: boolean }) { return (status === "DRAFT" && actions.canSubmit) || (status === "AWAITING_APPROVAL" && (actions.canApprove || actions.canCancel)) || (status === "DRAFT" && actions.canCancel) || (status === "CANCELLED" && actions.canCreate); }
function statusTruth(status: string) { if (status === "APPROVED") return "Approved for payment preparation only. It has not been submitted to a bank and is not paid."; if (status === "AWAITING_APPROVAL") return "Awaiting an authorized checker. No bank instruction exists."; if (status === "DRAFT") return "Prepared from locked payroll and masked bank snapshots. No money movement has occurred."; if (status === "CANCELLED") return "Cancelled without deleting historical instructions or events."; return "This status does not mean employees have been paid."; }
function InstructionFilters({ batchId, filters }: { batchId: string; filters: { blocker: string | null; query: string; status: string | null } }) { return <form action={`/team/payroll/payments/${batchId}`} className={styles.instructionFilters} method="get"><label><span>Search</span><input defaultValue={filters.query} maxLength={80} name="q" placeholder="Employee name, code, or reference" type="search" /></label><label><span>Status</span><select defaultValue={filters.status ?? ""} name="status"><option value="">All statuses</option>{paymentInstructionStatuses.map((status) => <option key={status} value={status}>{instructionStatusLabel(status)}</option>)}</select></label><label><span>Finding</span><select defaultValue={filters.blocker ?? ""} name="blocker"><option value="">All findings</option>{paymentInstructionBlockers.map((blocker) => <option key={blocker} value={blocker}>{blockerLabel(blocker)}</option>)}</select></label><button className={styles.primaryButton} type="submit">Apply</button>{filters.query || filters.status || filters.blocker ? <Link className={styles.secondaryButton} href={`/team/payroll/payments/${batchId}`}>Clear</Link> : null}</form>; }
function Pagination({ batchId, filters, page, totalPages }: { batchId: string; filters: { blocker: string | null; query: string; status: string | null }; page: number; totalPages: number }) { if (totalPages <= 1) return null; const href = (targetPage: number) => { const query = new URLSearchParams(); query.set("page", String(targetPage)); if (filters.query) query.set("q", filters.query); if (filters.status) query.set("status", filters.status); if (filters.blocker) query.set("blocker", filters.blocker); return `/team/payroll/payments/${batchId}?${query.toString()}`; }; return <nav className={styles.pagination}>{page > 1 ? <Link href={href(page - 1)}>Previous</Link> : <span>Previous</span>}<strong>Page {page} of {totalPages}</strong>{page < totalPages ? <Link href={href(page + 1)}>Next</Link> : <span>Next</span>}</nav>; }
