ALTER TABLE "services"
  ADD COLUMN "taxable" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "tax_rate" DECIMAL(5,2);

ALTER TABLE "invoices"
  ADD COLUMN "taxable_subtotal" DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN "tax_amount" DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN "tax_rate" DECIMAL(5,2) NOT NULL DEFAULT 0,
  ADD COLUMN "tax_label" TEXT;

ALTER TABLE "invoice_items"
  ADD COLUMN "taxable" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "tax_rate" DECIMAL(5,2) NOT NULL DEFAULT 0,
  ADD COLUMN "tax_amount" DECIMAL(10,2) NOT NULL DEFAULT 0;
